apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: autogov-workflows
  description: Dedicated reusable automated governance workflows.
  annotations:
    github.com/project-slug: liatrio/autogov-workflows
  tags:
    - autogov
    - automated-governance
    - github-actions
    - reusable-workflow
    - workflow
spec:
  owner: "group:default/tag-autogov"
  lifecycle: in-progress
  type: service
