name: Build Image Composite Action

description: >-
  A composite action that is placed in ./.github/actions/build-image/action.yaml whereby
  ./.github/workflows/rw-attest.yaml will trigger this action to build an image. The steps
  can be adjusted per the users need just as long as the output is the image digest.

inputs:
  subject-name:
    description: The name for the image.
    required: true
    default: ghcr.io/${{ github.repository }}
  build-context:
    description:
      Build's context is the set of files located in the specified PATH (the default Git context
      URL will not work since a repo checkout is needed to invoke the composite action / isolated build steps).
      A valid Dockerfile must be available in the PATH given.
    required: false
    default: .
  docker-file:
    description: Path to the Dockerfile. (default is {context}/Dockerfile).
    required: false
  platforms:
    description: List of target platforms for build.
    required: false
    default: linux/amd64,linux/arm64
  registry:
    description: Container registry to push image.
    required: false
    default: ghcr.io
outputs:
  image-digest:
    description: The image digest of the image that was built from the build-image job.
    value: ${{ steps.build-image.outputs.digest }}
  image-build-metadata:
    description: A JSON object with the build-image job's result metadata.
    value: ${{ steps.build-image.outputs.metadata }}

runs:
  using: composite
  steps:
    - name: Image Metadata
      id: meta
      uses: docker/metadata-action@8e5442c4ef9f78752691e2d8f8d19755c6f78e81 # v5.5.1
      with:
        images: ${{ inputs.subject-name }}
        tags: |
          type=ref,event=branch
          type=sha
          type=raw,value=latest,enable=${{ github.event_name == 'release' }}
          type=raw,value=${{ github.event.release.tag_name }},enable=${{ github.event_name == 'release' }}
    - name: Set up QEMU
      uses: docker/setup-qemu-action@49b3bc8e6bdd4a60e6116a5414239cba5943d3cf # v3.2.0
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@988b5a0280414f521da01fcc63a27aeeb4b104db # v3.6.1
    - name: Log in to GitHub Container Registry
      uses: docker/login-action@9780b0c442fbb1117ed29e0efdff1e18412f7567 # v3.3.0
      with:
        registry: ${{ inputs.registry }}
        username: ${{ github.actor }}
        password: ${{ github.token }}
    - name: Build and push Docker image
      uses: docker/build-push-action@4f58ea79222b3b9dc2c8bbdd6debcef730109a75 # v6.9.0
      id: build-image
      with:
        context: ${{ inputs.build-context }}
        file: ${{ inputs.docker-file }}
        push: true
        platforms: ${{ inputs.platforms }}
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        outputs: type=oci,dest=/tmp/image.tar
        cache-from: type=gha
        cache-to: type=gha,mode=max
      # ____________#
      # debug steps #
      # ____________#
    - name: Dump GitHub context
      shell: bash
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
      run: echo "$GITHUB_CONTEXT"
    - name: Dump job context
      shell: bash
      env:
        JOB_CONTEXT: ${{ toJson(job) }}
      run: echo "$JOB_CONTEXT"
    - name: Dump steps context
      shell: bash
      env:
        STEPS_CONTEXT: ${{ toJson(steps) }}
      run: echo "$STEPS_CONTEXT"
    - name: Dump runner context
      shell: bash
      env:
        RUNNER_CONTEXT: ${{ toJson(runner) }}
      run: echo "$RUNNER_CONTEXT"
    - name: Dump strategy context
      shell: bash
      env:
        STRATEGY_CONTEXT: ${{ toJson(strategy) }}
      run: echo "$STRATEGY_CONTEXT"
    - name: Dump matrix context
      shell: bash
      env:
        MATRIX_CONTEXT: ${{ toJson(matrix) }}
      run: echo "$MATRIX_CONTEXT"
    - name: Show default environment variables
      shell: bash
      run: |
        echo "The job_id is: $GITHUB_JOB"
        echo "The id of this action is: $GITHUB_ACTION"
        echo "The run id is: $GITHUB_RUN_ID"
        echo "The GitHub Actor's username is: $GITHUB_ACTOR"
        echo "GitHub SHA: $GITHUB_SHA"
    - name: List all GitHub environment variables
      shell: bash
      run: printenv | grep '^GITHUB_'
