name: Build Blob Composite Action

description: >-
  A composite action that is placed in ./.github/actions/build-blob/action.yaml whereby
  ./.github/workflows/rw-attest.yaml will trigger this action to build the blob(s). The steps
  can be adjusted per the users need just as long as the result blob file(s) is referenced for
  downstream jobs.

runs:
  using: composite
  steps:
    - name: Build Blob
      shell: bash
      run: |
        echo "i am a blob being created at $(date +'%Y-%m-%d %H:%M:%S') by ${{ github.triggering_actor }} by rw of
        ${{ github.workflow_ref }} in the repo of ${{ github.repository }} by the action known as ${{ github.action }}
        which may or may not live in the same repo as the action repo of ${{ github.action_repository || 'nothing to see here' }}." > i_am_blob && ls -alth  &&
        echo "$(date +'%Y-%m-%d %H:%M:%S') by ${{ github.triggering_actor }} by rw of
        ${{ github.workflow_ref }} in the repo of ${{ github.repository }}" > i_am_another_blob
