name: Build Blob Composite Action

description: >-
  composite action called by rw ./.github/workflows/rw-attest.yaml to do the thing / handing it over to gh's sigtore.
runs:
  using: composite
  steps:
    - name: Build Blob
      shell: bash
      run: |
        echo "i am a blob being created at $(date +'%Y-%m-%d') by ${{ github.triggering_actor }} by rw of ${{ github.workflow_ref }} in the repo of ${{ github.repository }} by the action known as ${{ github.action }} which may or may not live in the same repo as ${{ github.action_repository }}." > i_am_blob && ls -alt
