name: Attested Image Release

on:
  workflow_call:
    inputs:
      image_digest:
        type: string
        description: The digest of the image that was built and pushed
        required: true

env:
  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@9780b0c442fbb1117ed29e0efdff1e18412f7567 # v3.3.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ env.GH_TOKEN }}
      - name: Checkout workflow repo
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
        with:
          repository: liatrio/demo-gh-autogov-workflows
          ref: main
          fetch-depth: 0
          token: ${{ secrets.READ_CONTENT_GITHUB_TOKEN }}
      - name: check workflow repo
        id: check-workflow-repo
        if: ${{ github.repository == 'liatrio/demo-gh-autogov-workflows' }}
        run: |
          echo "in_autogov_workflow_repo=true" >> "$GITHUB_ENV"
      - name: Get latest commit SHA from branch
        id: get-sha
        run: |
          COMMIT_SHA=$(git rev-parse main)
          echo "COMMIT_SHA=$COMMIT_SHA" >> $GITHUB_ENV
      - name: Verify attestation without commit sha
        id: verify-without-sha
        if: ${{ env.in_autogov_workflow_repo == 'true' }}
        run: |
          gh attestation \
          verify \
          oci://ghcr.io/${{ github.repository }}@${{ inputs.image_digest }} \
          -o liatrio \
          --format json
      - name: Verify attestation with commit sha
        id: verify-with-sha
        if: ${{ env.in_autogov_workflow_repo != 'true' }}
        run: |
          gh attestation \
          verify \
          oci://ghcr.io/${{ github.repository }}@${{ inputs.image_digest }} \
          -o liatrio \
          --cert-identity-regex \
          "^https:\/\/github\.com\/liatrio\/demo-gh-autogov-workflows\/\.github\/workflows\/[^\/]+\.yaml@$COMMIT_SHA$" \
          --format json

  # haven't decided on what direction to go in regards to what to validate against / saving this as an alternative:
  # "^https:\/\/github\.com\/liatrio\/demo-gh-autogov-workflows\/\.github\/workflows\/[^\/]+\.yaml@[a-f0-9]{40}$" \

  run-opa:
    runs-on: ubuntu-latest
    needs: [verify]
    steps:
      - name: Check out repository code
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@9780b0c442fbb1117ed29e0efdff1e18412f7567 # v3.3.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ env.GH_TOKEN }}
      - name: Setup OPA
        uses: open-policy-agent/setup-opa@34a30e8a924d1b03ce2cf7abe97250bbb1f332b5 # v2.2.0
        with:
          version: 0.67.1
      - name: Download artifact attestation
        id: download-attestations
        run: |
          gh attestation \
          download \
          oci://ghcr.io/${{ github.repository }}@${{ inputs.image_digest }} \
          -o liatrio
      - name: Download Policy Bundle
        run: |
          asset_url=$(curl -L -H "Authorization: Bearer ${{ secrets.READ_CONTENT_GITHUB_TOKEN }}" https://api.github.com/repos/liatrio/demo-gh-autogov-policy-library/releases/latest | jq -r '.assets[] | select(.name == "bundle.tar.gz") | .url')
          curl -L -o bundle.tar.gz -H "Accept: application/octet-stream" -H "Authorization: Bearer ${{ secrets.READ_CONTENT_GITHUB_TOKEN }}" $asset_url
      - name: Run OPA Evals
        id: run-opa-evals
        run: |
          opa eval \
          --fail \
          --input ${{ inputs.image_digest }}.jsonl \
          --bundle bundle.tar.gz \
          "data.governance.all_passed" > policy-evaluation-raw.json
          cat policy-evaluation-raw.json
      - name: Save evaluation results as artifact
        if: success() || failure()
        uses: actions/upload-artifact@50769540e7f4bd5e21e526ee35c689e35e0d6874 # v4.4.0
        with:
          name: results
          path: policy-evaluation-raw.json

  results:
    runs-on: ubuntu-latest
    needs: [verify, run-opa]
    steps:
      - name: Download Results
        uses: actions/download-artifact@fa0a91b85d4f404e444e00e005971372dc801d16 # v4.1.8
        with:
          name: results
          path: .
      - name: Format Results
        run: |
          jq '{
            result: (
              if ([.result[].expressions[].value] | any(. == false)) then "FAILED" else "PASSED" end
            ),
            violations: (
              [.result[].expressions[]
                | select(.value == false)
                | {
                    "Policy Set": (.text | split(".") | .[1] + "." + .[2]),
                    "Results": .value
                  }
              ]
            )
          }' policy-evaluation-raw.json > policy-evaluation.json
          cat policy-evaluation.json
          jq -s 'reduce .[] as $item ({}; . * $item)' policy-evaluation.json > results
          cat results

          echo "### Policy Evaluation Summary" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "#### Result: $(jq -r '.result' results)" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
      - name: Save evaluation results as artifact
        if: success() || failure()
        uses: actions/upload-artifact@50769540e7f4bd5e21e526ee35c689e35e0d6874 # v4.4.0
        with:
          name: results_artifact
          path: results

  release:
    runs-on: ubuntu-latest
    needs: [verify, results]
    permissions:
      contents: write
    steps:
      - name: Download Results
        uses: actions/download-artifact@fa0a91b85d4f404e444e00e005971372dc801d16 # v4.1.8
        with:
          name: results
          path: .
      - name: Run go-semantic-release
        uses: go-semantic-release/action@48d83acd958dae62e73701aad20a5b5844a3bf45 # v1.23.0
        id: go-semantic-release
        with:
          github-token: ${{ env.GH_TOKEN }}
          changelog-generator-opt: emojis=true
          allow-initial-development-versions: true
      - name: Upload Release Asset
        if: steps.go-semantic-release.outputs.version != ''
        uses: softprops/action-gh-release@c062e08bd532815e2082a85e87e3ef29c3e6d191 # v2.0.8
        with:
          files: results
          tag_name: v${{ steps.go-semantic-release.outputs.version }}
          token: ${{ env.GH_TOKEN }}
