name: Build / Attest Image

on:
  workflow_call:
    inputs:
      image_digest:
        type: string
        description: The digest of the image that was built and pushed
        required: true

jobs:
  attest-image:
    runs-on: ubuntu-latest
    steps:
      - name: Log in to GitHub Container Registry
        uses: ./.github/actions/login-ghcr
        with:
          gh_token: ${{ secrets.GITHUB_TOKEN }}
      - name: Attest Provenance
        uses: actions/attest-build-provenance@1c608d11d69870c2092266b3f9a6f3abbf17002c # v1.4.3
        id: attest-build-provenance
        with:
          subject-name: ghcr.io/${{ github.repository }}
          subject-digest: ${{ inputs.image_digest }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          push-to-registry: true
