name: Attested Image Release

on:
  workflow_call:
    inputs:
      image_digest:
        type: string
        description: The digest of the image that was built and pushed
        required: true

jobs:
  results:
    runs-on: ubuntu-latest
    steps:
      - name: Download Results
        uses: actions/download-artifact@fa0a91b85d4f404e444e00e005971372dc801d16 # v4.1.8
        with:
          name: results
          path: .
      - name: Format Results
        run: |
          jq '{
            result: (
              if ([.result[].expressions[].value] | any(. == false)) then "FAILED" else "PASSED" end
            ),
            violations: (
              [.result[].expressions[]
                | select(.value == false)
                | {
                    "Policy Set": (.text | split(".") | .[1] + "." + .[2]),
                    "Results": .value
                  }
              ]
            )
          }' policy-evaluation.json > results
          cat results | jq -r

          echo "### Policy Evaluation Summary" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "#### Result: $(jq -r '.result' results)" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
      - name: Save evaluation results as artifact
        if: success() || failure()
        uses: actions/upload-artifact@50769540e7f4bd5e21e526ee35c689e35e0d6874 # v4.4.0
        with:
          name: results_artifact
          path: results

  release:
    runs-on: ubuntu-latest
    needs: [results]
    permissions:
      contents: write
    steps:
      - name: Download Results
        uses: actions/download-artifact@fa0a91b85d4f404e444e00e005971372dc801d16 # v4.1.8
        with:
          name: results_artifact
          path: .
      - name: Run go-semantic-release
        uses: go-semantic-release/action@48d83acd958dae62e73701aad20a5b5844a3bf45 # v1.23.0
        id: go-semantic-release
        with:
          github-token: ${{ github.token }}
          changelog-generator-opt: emojis=true
          allow-initial-development-versions: true
      - name: Upload Release Asset
        if: steps.go-semantic-release.outputs.version != ''
        uses: softprops/action-gh-release@c062e08bd532815e2082a85e87e3ef29c3e6d191 # v2.0.8
        with:
          files: results
          tag_name: v${{ steps.go-semantic-release.outputs.version }}
          token: ${{ github.token }}
