name: Build Image Caller Workflow

on:
  workflow_dispatch:
  release:
    types: [published]
  pull_request:
    types: [opened, synchronize, reopened]
    branches: [main]

permissions: {}

jobs:
  attest-image: #image
    permissions:
      id-token: write
      attestations: write
      packages: write
      contents: write
      actions: read
    uses: ./.github/workflows/rw-attest.yaml
    with:
      build-type: image
      subject-name: ghcr.io/${{ github.repository }}
  verify-image: #image
    permissions:
      id-token: write
      attestations: read
      packages: read
    needs: [attest-image]
    uses: ./.github/workflows/rw-verify.yaml
    secrets: inherit
    with:
      build-type: image
      image-digest: ${{ needs.attest-image.outputs.image-digest }}
      cert-identity: https://github.com/liatrio/demo-gh-autogov-workflows/.github/workflows/rw-attest.yaml@${{ github.ref }}
  run-opa-image: #image
    permissions:
      attestations: read
      id-token: write
      # packages: write is to delete stale images / read is only necessary for everything prior
      packages: write
    needs: [verify-image, attest-image]
    uses: ./.github/workflows/rw-run-opa.yaml
    secrets: inherit
    with:
      build-type: image
      image-digest: ${{ needs.attest-image.outputs.image-digest }}

