name: Build Blob Caller Workflow

on:
  workflow_dispatch:
  pull_request:
    types: [opened, synchronize, reopened]
    branches: [main]
  # push:

jobs:
  attest-blob: #blob
    uses: ./.github/workflows/rw-attest.yaml
    with:
      build-type: blob
      subject-path: i_am_blob
  verify-blob: #blob
    needs: [attest-blob]
    uses: ./.github/workflows/rw-verify.yaml
    secrets: inherit
    with:
      build-type: blob
      build-artifact-id: ${{ needs.attest-blob.outputs.build-artifact-id }}
  run-opa-blob: #blob
    needs: [verify-blob, attest-blob]
    uses: ./.github/workflows/rw-run-opa.yaml
    secrets: inherit
    with:
      build-type: blob
      build-artifact-id: ${{ needs.attest-blob.outputs.build-artifact-id }}
