name: Caller Workflow

on:
  workflow_dispatch:
  release:
    types: [published]
  pull_request:
    types: [opened, synchronize, reopened]
    branches: main

jobs:
  attest:
    uses: ./.github/workflows/rw-attest.yaml
    with:
      build-type: image
  verify:
    needs: [attest]
    uses: ./.github/workflows/rw-verify.yaml
    secrets: inherit
    with:
      image_digest: ${{ needs.attest.outputs.image_digest }}
  run-opa:
    needs: [verify, attest]
    uses: ./.github/workflows/rw-run-opa.yaml
    secrets: inherit
    with:
      image_digest: ${{ needs.attest.outputs.image_digest }}
