name: Pull Request Check and Release

on:
  workflow_dispatch:
  # pull_request:
  #   types: [opened, synchronize, reopened]
  #   branches:
  #     - '**'
  push:
    branches:
      - main
    paths-ignore:
      - 'README.md'
      - 'catalog-info.yaml'

permissions:
  id-token: write
  attestations: write
  packages: write
  contents: write

jobs:
  build-image:
    uses: ./.github/workflows/build-image.yaml
  attest-image:
    uses: ./.github/workflows/attest-image.yaml
    needs: build-image
    secrets: inherit
    with:
      image_digest: ${{ needs.build-image.outputs.image_digest }}
  attest-sbom:
    uses: ./.github/workflows/attest-sbom.yaml
    needs: build-image
    secrets: inherit
    with:
      image_digest: ${{ needs.build-image.outputs.image_digest }}
  attest-blob:
    uses: ./.github/workflows/attest-blob.yaml
    needs: build-image
    secrets: inherit
    with:
      image_digest: ${{ needs.build-image.outputs.image_digest }}
  verify:
    uses: ./.github/workflows/verify.yaml
    needs: [build-image, attest-image, attest-sbom, attest-blob]
    secrets: inherit
    with:
      image_digest: ${{ needs.build-image.outputs.image_digest }}
  run-opa:
    uses: ./.github/workflows/run-opa.yaml
    needs: [build-image, verify]
    secrets: inherit
    with:
      image_digest: ${{ needs.build-image.outputs.image_digest }}
  release:
    uses: ./.github/workflows/attested-image-release.yaml
    needs: [build-image, run-opa]
    secrets: inherit
    with:
      image_digest: ${{ needs.build-image.outputs.image_digest }}
