name: Reusable Build Image / Attest Workflow

on:
  workflow_call:
    inputs:
      build-type:
        description: 'Specify the type of build: "image" or "blob".'
        required: true
        default: 'image'
        type: string
      subject-name:
        description: >
          Subject name as it should appear in the attestation. Required unless
          "subject-path" is specified, in which case it will be inferred from the
          path.
        required: false
        type: string
      blob-artifact-name:
        description: >
          The name of the blob(s) built from the build-blob action found in
          ./.github/actions/build-blob/action.yaml.
        default: blob-build-artifact
        required: false
        type: string
      subject-path:
        description: >
          Path to the artifact serving as the subject of the attestation. Must
          specify exactly one of "subject-path" or "subject-digest". May contain a
          glob pattern or list of paths (total subject count cannot exceed 2500).
          examples: https://github.com/actions/attest-build-provenance?tab=readme-ov-file#examples
        default: |
          i_am_blob
        required: false
        type: string
      show-summary:
        description: >
          Whether to attach a list of generated attestations to the workflow run
          summary page. Defaults to true.
        default: true
        required: false
        type: boolean
      registry:
        description: Container registry to push image.
        required: false
        default: ghcr.io
        type: string
      workflow-runner-label:
        description: >
          The label used for runner/OS selection
          examples: https://docs.github.com/en/actions/writing-workflows/choosing-where-your-workflow-runs/choosing-the-runner-for-a-job#example-specifying-an-operating-system.
        required: false
        default: ubuntu-latest
        type: string
      signer-workflow-cert-identity:
        description: >
          The signer workflow's identity used to validate against the Subject Alternative Name (SAN) within the attestation certificate.
          The --cert-identity is the most effective/reliable means to validate the certificate, or workflow (e.g. signer workflow's identity).
        required: false
        default: https://github.com/liatrio/demo-gh-autogov-workflows/.github/workflows/rw-attest.yaml@refs/heads/main
        type: string
      predicate-type:
        description: >
          The type of attestation predicate.
        required: false
        type: string
        default: 'https://cosign.sigstore.dev/attestation/v1'
      sbom-format:
        description: >
          The format of the SBOM.
        required: false
        type: string
        default: 'cyclonedx-json'
      sbom-output-file:
        description: >
          The output file for the SBOM.
        required: false
        type: string
        default: 'sbom.cyclonedx.json'
      sbom-path:
        description: >
          The path to the SBOM file.
        required: false
        type: string
        default: 'sbom.cyclonedx.json'
    outputs:
      image-digest:
        description: The image digest of the image that was built from the build-image job.
        value: ${{ inputs.build-type == 'image' && jobs.build.outputs.image-digest }}
      image-build-metadata:
        description: A JSON object with the build-image job's result metadata.
        value: ${{ inputs.build-type == 'image' && jobs.build.outputs.image-build-metadata }}
      build-artifact-id:
        description: The artifact-id of the build artifacts.
        value: ${{ inputs.build-type == 'blob' && jobs.build.outputs.build-artifact-id }}

permissions: {}

jobs:
  build:
    permissions:
      contents: read
      packages: write
    runs-on: ${{ inputs.workflow-runner-label }}
    outputs:
      image-digest: ${{ steps.build-image.outputs.image-digest }}
      image-build-metadata: ${{ steps.build-image.outputs.image-build-metadata }}
      job-id: ${{ github.job }}
      build-artifact-id: ${{ steps.upload-blob.outputs.artifact-id }}
    steps:
      - name: Check runner type
        if: ${{ runner.environment != 'github-hosted' }}
        run: |
          echo "Job is running on a self-hosted runner. Terminating job..."
          exit 1
      - name: Checkout code
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
      - name: Build Image
        if: ${{ runner.environment == 'github-hosted' && inputs.build-type == 'image' }}
        id: build-image
        uses: ./.github/actions/build-image
        with:
          build-context: ${{ inputs.build-context }}
          subject-name: ${{ inputs.subject-name }}
          docker-file: ${{ inputs.docker-file }}
          platforms: ${{ inputs.platforms }}
      - name: Build Blob
        if: ${{ runner.environment == 'github-hosted' && inputs.build-type == 'blob' }}
        id: build-blob
        uses: ./.github/actions/build-blob
      - run: |
        if: ${{ inputs.build-type == 'blob' }}
          set +x
          ls -alth
          cat i_am_blob
      - name: Upload Blob
        if: ${{ inputs.build-type == 'blob' }}
        id: upload-blob
        uses: actions/upload-artifact@50769540e7f4bd5e21e526ee35c689e35e0d6874 #v4.4.0
        with:
          name: ${{ inputs.blob-artifact-name }}
          path: ${{ inputs.subject-path }}
          if-no-files-found: error
      - name: DEBUG THE THINGS
        run: |
          set +x
          echo "Image Digest: ${{ steps.build-image.outputs.image-digest }}"
          echo "Image Build Metadata: $(echo '${{ toJson(steps.build-image.outputs.image-build-metadata) }}' | jq .)"
          echo "Runner: $(echo '${{ toJson(runner) }}' | jq .)"
      #     echo "GitHub: $(echo '${{ toJson(github) }}' | jq .)"

  attest-build:
    runs-on: ${{ inputs.workflow-runner-label }}
    needs: build
    permissions:
      id-token: write
      attestations: write
      packages: write
      contents: read
    env:
      ARTIFACTS_FOLDER: ./artifacts
      ATTESTATIONS_FOLDER: ./attestations
    outputs:
      build-artifact-id: ${{ steps.upload-provenance.outputs.artifact-id }}
    steps:
      - name: Check runner type
        if: ${{ runner.environment != 'github-hosted' }}
        run: |
          echo "Job is running on a self-hosted runner. Terminating job..."
          exit 1
      - name: Log in to GitHub Container Registry
        if: ${{ runner.environment == 'github-hosted' && inputs.build-type == 'image' }}
        uses: docker/login-action@9780b0c442fbb1117ed29e0efdff1e18412f7567 # v3.3.0
        with:
          registry: ${{ inputs.registry }}
          username: ${{ github.actor }}
          password: ${{ github.token }}
      - run: npm install @actions/artifact@2.1.9
        if: ${{ runner.environment == 'github-hosted' && inputs.build-type == 'blob' }}
      - name: download-artifact
        if: ${{ inputs.build-type == 'blob' }}
        uses: actions/github-script@60a0d83039c74a4aee543508d2ffcb1c3799cdea # v7.0.1
        env:
          ARTIFACT_ID: ${{ needs.build.outputs.build-artifact-id }}
          ARTIFACTS_FOLDER: ./artifacts
        with:
          script: |
            const { DefaultArtifactClient } = require('@actions/artifact');
            const artifactClient = new DefaultArtifactClient();
            const artifactId = process.env.ARTIFACT_ID;

            if (!artifactId) {
              throw new Error('Artifact ID is not defined');
            }

            await artifactClient.downloadArtifact(artifactId, { path: process.env.ARTIFACTS_FOLDER });
            console.log(`Downloaded artifact with ID: ${artifactId} to ${process.env.ARTIFACTS_FOLDER}`);
      - name: List downloaded artifacts
        if: ${{ inputs.build-type == 'blob' }}
        run: ls -althR ./artifacts
      - name: Attest Provenance
        id: attest-build-provenance
        uses: actions/attest-build-provenance@1c608d11d69870c2092266b3f9a6f3abbf17002c # v1.4.3
        with:
          subject-name: ${{ inputs.build-type == 'image' && inputs.subject-name || '' }}
          subject-digest: ${{ inputs.build-type == 'image' && needs.build.outputs.image-digest || '' }}
          subject-path: ${{ inputs.build-type == 'blob' && format('./artifacts/{0}', inputs.subject-path) || '' }}
          github-token: ${{ github.token }}
          push-to-registry: ${{ inputs.build-type == 'image' && 'true' || 'false' }}
      - name: Rename Provenance Bundle
        run: |
          mkdir ./attestations
          mv ${{ steps.attest-build-provenance.outputs.bundle-path }} ./attestations/attest-build-provenance-attestation.jsonl
      - name: Upload Provenance Sigstore Bundle
        id: upload-provenance
        uses: actions/upload-artifact@834a144ee995460fba8ed112a2fc961b36a5ec5a #v4.3.6
        with:
          name: attest-build-provenance
          path: ./attestations/attest-build-provenance-attestation.jsonl

  attest-metadata:
    runs-on: ${{ inputs.workflow-runner-label }}
    needs: build
    permissions:
      id-token: write
      attestations: write
      packages: write
      contents: read
    outputs:
      build-artifact-id: ${{ steps.upload-metadata.outputs.artifact-id }}
    steps:
      - name: Check runner type
        if: ${{ runner.environment != 'github-hosted' }}
        run: |
          echo "Job is running on a self-hosted runner. Terminating job..."
          exit 1
      - name: Log in to GitHub Container Registry
        if: ${{ runner.environment == 'github-hosted' && inputs.build-type == 'image' }}
        uses: docker/login-action@9780b0c442fbb1117ed29e0efdff1e18412f7567 # v3.3.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}
      - run: npm install @actions/artifact@2.1.9
        if: ${{ runner.environment == 'github-hosted' && inputs.build-type == 'blob' }}
      - name: download-artifact
        if: ${{ inputs.build-type == 'blob' }}
        uses: actions/github-script@60a0d83039c74a4aee543508d2ffcb1c3799cdea # v7.0.1
        env:
          ARTIFACT_ID: ${{ needs.build.outputs.build-artifact-id }}
          ARTIFACTS_FOLDER: ./artifacts
        with:
          script: |
            const { DefaultArtifactClient } = require('@actions/artifact');
            const artifactClient = new DefaultArtifactClient();
            const artifactId = process.env.ARTIFACT_ID;

            if (!artifactId) {
              throw new Error('Artifact ID is not defined');
            }

            await artifactClient.downloadArtifact(artifactId, { path: process.env.ARTIFACTS_FOLDER });
            console.log(`Downloaded artifact with ID: ${artifactId} to ${process.env.ARTIFACTS_FOLDER}`);
      - name: List downloaded artifacts
        if: ${{ inputs.build-type == 'blob' }}
        run: ls -althR ./artifacts
      - run: |
          echo ${{ github.workflow }}
          echo ${{ github.workflow_ref }}
          echo ${{ github.workflow_sha }}
          echo ${{ github.workspace }}
          echo ${{ github.action_repository || 'nothing to see here' }}
          echo ${{ github.triggering_actor }}
          echo ${{ github.event_name }}
      - name: Generate Metadata Attestation
        run: |
          echo '{
            "_type": "https://in-toto.io/Statement/v0.1",
            "metadata": {
              "workflowRunId": "${{ github.run_id }}",
              "commitSHA": "${{ github.sha }}",
              "githubServerURL": "${{ github.server_url }}",
              "repository": "${{ github.repository }}",
              "repositoryId": "${{ github.repository_id }}",
              "owner": "${{ github.repository_owner }}",
              "ownerId": "${{ github.repository_owner_id }}",
              "actor": "${{ github.actor }}",
              "event": "${{ github.event_name }}",
              "ref": "${{ github.ref }}",
              "jobId": "${{ github.job }}",
              "runNumber": "${{ github.run_number }}",
              "workflowRefPath": "${{ github.workflow_ref }}",
              "action": "${{ github.action }}",
              "runnerOS": "${{ runner.os }}",
              "runnerName": "${{ runner.name }}",
              "commitTimestamp": "${{ github.event.head_commit.timestamp }}"
            }
          }' > metadata.json
      - run: cat metadata.json | jq -r
      - uses: actions/attest@67422f5511b7ff725f4dbd6fb9bd2cd925c65a8d # v1.4.1
        id: attest-metadata
        with:
          predicate-type: ${{ inputs['predicate-type'] }}
          predicate-path: metadata.json
          push-to-registry: ${{ inputs.build-type == 'image' && 'true' || 'false' }}
          subject-name: ${{ inputs.build-type == 'image' && inputs['subject-name'] || '' }}
          subject-digest: ${{ inputs.build-type == 'image' && needs.build.outputs.image-digest || '' }}
          subject-path: ${{ inputs.build-type == 'blob' && format('./artifacts/{0}', inputs.subject-path) || '' }}
      - name: Rename Metadata Bundle
        run: |
          mkdir ./attestations
          mv ${{ steps.attest-metadata.outputs.bundle-path }} ./attestations/attest-metadata-attestation.jsonl
      - name: Upload Metadata Sigstore Bundle
        uses: actions/upload-artifact@834a144ee995460fba8ed112a2fc961b36a5ec5a #v4.3.6
        id: upload-metadata
        with:
          name: ${{ inputs.build-type == 'image' && 'image-metadata-attestation' || inputs.build-type == 'blob' && 'blob-metadata-attestation' }}
          path: ./attestations/attest-metadata-attestation.jsonl
          if-no-files-found: error

  attest-sbom:
    runs-on: ${{ inputs.workflow-runner-label }}
    needs: [build, attest-metadata, attest-build]
    permissions:
      id-token: write
      attestations: write
      packages: write
      # the below permissions are required for a private repo to read the sbom so it can upload
      # https://github.com/anchore/sbom-action/issues/468#issuecomment-2126467656
      contents: write
      actions: read
    outputs:
      build-artifact-id: ${{ steps.upload-sbom.outputs.artifact-id }}
    steps:
      - name: Check runner type
        if: ${{ runner.environment != 'github-hosted' }}
        run: |
          echo "Job is running on a self-hosted runner. Terminating job..."
          exit 1
      - name: Log in to GitHub Container Registry
        if: ${{ runner.environment == 'github-hosted' && inputs.build-type == 'image' }}
        uses: docker/login-action@9780b0c442fbb1117ed29e0efdff1e18412f7567 # v3.3.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}
      - run: npm install @actions/artifact@2.1.9
        if: ${{ runner.environment == 'github-hosted' && inputs.build-type == 'blob' }}
      - name: download-artifact
        if: ${{ inputs.build-type == 'blob' }}
        uses: actions/github-script@60a0d83039c74a4aee543508d2ffcb1c3799cdea # v7.0.1
        env:
          ARTIFACT_ID: ${{ needs.build.outputs.build-artifact-id }}
          ARTIFACTS_FOLDER: ./artifacts
        with:
          script: |
            const { DefaultArtifactClient } = require('@actions/artifact');
            const artifactClient = new DefaultArtifactClient();
            const artifactId = process.env.ARTIFACT_ID;

            if (!artifactId) {
              throw new Error('Artifact ID is not defined');
            }

            await artifactClient.downloadArtifact(artifactId, { path: process.env.ARTIFACTS_FOLDER });
            console.log(`Downloaded artifact with ID: ${artifactId} to ${process.env.ARTIFACTS_FOLDER}`);
      - name: List downloaded artifacts
        if: ${{ inputs.build-type == 'blob' }}
        run: ls -althR ./artifacts
      - name: Generate SBOM
        uses: anchore/sbom-action@61119d458adab75f756bc0b9e4bde25725f86a7a # v0.17.2
        with:
          image: ${{ inputs.build-type == 'image' && format('{0}/{1}@{2}', inputs.registry, github.repository, needs.build.outputs.image-digest) || '' }}
          path: ${{ inputs.build-type == 'blob' && './artifacts' || '' }}
          file: ${{ inputs.build-type == 'blob' && format('./artifacts/{0}', inputs.subject-path) || '' }}
          format: ${{ inputs['sbom-format'] }}
          output-file: ${{ inputs['sbom-output-file'] }}
          github-token: ${{ github.token }}
      - name: Log SBOM File
        run: cat ${{ inputs['sbom-output-file'] }} | jq -r
      - name: Generate SBOM attestation
        id: attest-sbom
        uses: actions/attest-sbom@5026d3663739160db546203eeaffa6aa1c51a4d6 # v1.4.1
        with:
          subject-name: ${{ inputs.build-type == 'image' && inputs['subject-name'] || '' }}
          subject-digest: ${{ inputs.build-type == 'image' && needs.build.outputs.image-digest || '' }}
          subject-path: ${{ inputs.build-type == 'blob' && format('./artifacts/{0}', inputs.subject-path) || '' }}
          sbom-path: ${{ inputs['sbom-path'] }}
          github-token: ${{ github.token }}
          push-to-registry: ${{ inputs.build-type == 'image' && 'true' || 'false' }}
      - name: Rename SBOM Bundle
        run: |
          mkdir ./attestations
          mv ${{ steps.attest-sbom.outputs.bundle-path }} ./attestations/attest-sbom-attestation.jsonl
      - name: Upload SBOM Attestation
        id: upload-sbom
        uses: actions/upload-artifact@834a144ee995460fba8ed112a2fc961b36a5ec5a #v4.3.6
        with:
          name: attest-sbom
          path: ./attestations/attest-sbom-attestation.jsonl

  upload-attestations:
    runs-on: ${{ inputs.workflow-runner-label }}
    needs: [attest-build, attest-metadata, attest-sbom]
    env:
      ARTIFACTS_FOLDER: ./attestations
    steps:
      - run: npm install @actions/artifact@2.1.9
      - name: Download Provenance Attestation
        uses: actions/github-script@60a0d83039c74a4aee543508d2ffcb1c3799cdea # v7.0.1
        env:
          ARTIFACT_ID: ${{ needs.attest-build.outputs.build-artifact-id }}
        with:
          script: |
            const { DefaultArtifactClient } = require('@actions/artifact');
            const artifactClient = new DefaultArtifactClient();
            const artifactId = process.env.ARTIFACT_ID;

            if (!artifactId) {
              throw new Error('Artifact ID is not defined');
            }

            await artifactClient.downloadArtifact(artifactId, { path: process.env.ARTIFACTS_FOLDER });
            console.log(`Downloaded artifact with ID: ${artifactId} to ${process.env.ARTIFACTS_FOLDER}`);
      - name: Download Metadata Attestation
        uses: actions/github-script@60a0d83039c74a4aee543508d2ffcb1c3799cdea # v7.0.1
        env:
          ARTIFACT_ID: ${{ needs.attest-metadata.outputs.build-artifact-id }}
        with:
          script: |
            const { DefaultArtifactClient } = require('@actions/artifact');
            const artifactClient = new DefaultArtifactClient();
            const artifactId = process.env.ARTIFACT_ID;

            if (!artifactId) {
              throw new Error('Artifact ID is not defined');
            }

            await artifactClient.downloadArtifact(artifactId, { path: process.env.ARTIFACTS_FOLDER });
            console.log(`Downloaded artifact with ID: ${artifactId} to ${process.env.ARTIFACTS_FOLDER}`);
      - name: Download SBOM Attestation
        uses: actions/github-script@60a0d83039c74a4aee543508d2ffcb1c3799cdea # v7.0.1
        env:
          ARTIFACT_ID: ${{ needs.attest-sbom.outputs.build-artifact-id }}
        with:
          script: |
            const { DefaultArtifactClient } = require('@actions/artifact');
            const artifactClient = new DefaultArtifactClient();
            const artifactId = process.env.ARTIFACT_ID;

            if (!artifactId) {
              throw new Error('Artifact ID is not defined');
            }

            await artifactClient.downloadArtifact(artifactId, { path: process.env.ARTIFACTS_FOLDER });
            console.log(`Downloaded artifact with ID: ${artifactId} to ${process.env.ARTIFACTS_FOLDER}`);
      - name: Upload All Attestations
        id: all-attestations
        uses: actions/upload-artifact@834a144ee995460fba8ed112a2fc961b36a5ec5a #v4.3.6
        with:
          name: all-attestations
          path: ./attestations/*.jsonl
          if-no-files-found: error
