name: Reusable Build Image / Attest Workflow

on:
  workflow_call:
    outputs:
      image_digest:
        description: The digest of the image that was built and pushed
        value: ${{ jobs.build-image.outputs.image_digest }}

permissions: {}

jobs:
  build-image:
    permissions:
      contents: read
      packages: write
    runs-on: ubuntu-latest
    outputs:
      image_digest: ${{ steps.build-image.outputs.image_digest }}
    steps:
      - name: Check runner type
        if: ${{ runner.environment != 'github-hosted' }}
        run: |
          echo "Job is running on a self-hosted runner. Terminating job..."
          exit 1
        continue-on-error: false
      - name: Checkout code
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
      - name: Run build image composite action
        if: ${{ runner.environment == 'github-hosted' }}
        id: build-image
        uses: ./.github/actions/build-image
  attest-image:
    runs-on: ubuntu-latest
    needs: build-image
    permissions:
      id-token: write
      attestations: write
      packages: write
      contents: read
    steps:
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@9780b0c442fbb1117ed29e0efdff1e18412f7567 # v3.3.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}
      - name: Attest Provenance
        uses: actions/attest-build-provenance@1c608d11d69870c2092266b3f9a6f3abbf17002c # v1.4.3
        with:
          subject-name: ghcr.io/${{ github.repository }}
          subject-digest: ${{ needs.build-image.outputs.image_digest }}
          github-token: ${{ github.token }}
          push-to-registry: true
  attest-blob:
    runs-on: ubuntu-latest
    needs: build-image
    permissions:
      id-token: write
      attestations: write
      packages: write
      contents: read
    steps:
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@9780b0c442fbb1117ed29e0efdff1e18412f7567 # v3.3.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}
      - run: |
          echo ${{ github.workflow }}
          echo ${{ github.workflow_ref }}
          echo ${{ github.workflow_sha }}
          echo ${{ github.workspace }}
          echo ${{ github.action_repository }}
          echo ${{ github.triggering_actor }}
          echo ${{ github.event_name }}
      - name: Generate Metadata Attestation for Image
        run: |
          echo '{
            "_type": "https://in-toto.io/Statement/v0.1",
            "predicateType": "https://cosign.sigstore.dev/attestation/v1",
            "subject": [
              {
                "name": "ghcr.io/${{ github.repository }}",
                "digest": {
                  "sha256": "${{ inputs.image_digest }}"
                }
              }
            ],
            "metadata": {
              "workflowRunId": "${{ github.run_id }}",
              "commitSHA": "${{ github.sha }}",
              "githubServerURL": "${{ github.server_url }}",
              "repository": "${{ github.repository }}",
              "repositoryId": "${{ github.repository_id }}",
              "owner": "${{ github.repository_owner }}",
              "ownerId": "${{ github.repository_owner_id }}",
              "actor": "${{ github.actor }}",
              "event": "${{ github.event_name }}",
              "ref": "${{ github.ref }}",
              "jobId": "${{ github.job }}",
              "runNumber": "${{ github.run_number }}",
              "workflowRefPath": "${{ github.workflow_ref }}",
              "action": "${{ github.action }}",
              "runnerOS": "${{ runner.os }}",
              "runnerName": "${{ runner.name }}",
              "commitTimestamp": "${{ github.event.head_commit.timestamp }}"
            }
          }' > metadata.json
      - run: cat metadata.json | jq -r
      - uses: actions/attest@67422f5511b7ff725f4dbd6fb9bd2cd925c65a8d # v1.4.1
        with:
          predicate-type: 'https://cosign.sigstore.dev/attestation/v1'
          predicate-path: 'metadata.json'
          subject-name: ghcr.io/${{ github.repository }}
          subject-digest: ${{ needs.build-image.outputs.image_digest }}
          push-to-registry: true
  attest-sbom:
    runs-on: ubuntu-latest
    needs: build-image
    permissions:
      id-token: write
      attestations: write
      packages: write
      actions: read # required for a private repo to read the sbom once it's generated so it can upload as per https://github.com/anchore/sbom-action/issues/468#issuecomment-2126467656
      contents: read
    steps:
      - name: Checkout code
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@9780b0c442fbb1117ed29e0efdff1e18412f7567 # v3.3.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}
      - name: Generate SBOM
        uses: anchore/sbom-action@61119d458adab75f756bc0b9e4bde25725f86a7a # v0.17.2
        with:
          image: ghcr.io/${{ github.repository }}@${{ needs.build-image.outputs.image_digest }}
          format: 'cyclonedx-json'
          output-file: 'sbom.cyclonedx.json'
      - name: Log SBOM File
        run: cat sbom.cyclonedx.json | jq -r
      - name: Generate SBOM attestation
        uses: actions/attest-sbom@5026d3663739160db546203eeaffa6aa1c51a4d6 # v1.4.1
        with:
          subject-name: ghcr.io/${{ github.repository }}
          subject-digest: ${{ needs.build-image.outputs.image_digest }}
          sbom-path: 'sbom.cyclonedx.json'
          github-token: ${{ github.token }}
          push-to-registry: true
