name: Attest Image Reusable Workflow

on:
  workflow_call:
    inputs:
      subject-name:
        description: >
          Subject name as it should appear in the attestation. Required unless
          "subject-path" is specified, in which case it will be inferred from the
          path.
        required: true
        type: string
      registry:
        description: Container registry to push image.
        default: ghcr.io
        required: true
        type: string
      show-summary:
        description: >
          Whether to attach a list of generated attestations to the workflow run
          summary page. Defaults to true.
        default: true
        required: false
        type: boolean
      workflow-runner-label:
        description: >
          The label used for runner/OS selection, examples:
          https://docs.github.com/en/actions/writing-workflows/choosing-where-your-workflow-runs/choosing-the-runner-for-a-job#example-specifying-an-operating-system.
        default: ubuntu-latest
        required: false
        type: string
      github-token:
        description: >
          The GitHub token set throughout the reusable workflow including the composite (build) action.
        required: false
        type: string
      autogov-version:
        description: The autogov version to use for predicate generation.
        required: false
        type: string
        default: v0.20.0
    outputs:
      image-digest:
        description: The image digest of the image that was built from the build-image job.
        value: ${{ jobs.build-high-perms.outputs.image-digest }}
      attest-build-attestation-artifact-id:
        description: The artifact-id of the build provenance attestation artifact.
        value: ${{ jobs.attest-build-high-perms.outputs.provenance-artifact-id }}
      attest-metadata-attestation-artifact-id:
        description: The artifact-id of the custom metadata attestation artifact.
        value: ${{ jobs.attest-metadata-high-perms.outputs.metadata-artifact-id }}
      attest-sbom-attestation-artifact-id:
        description: The artifact-id of the SBOM attestation artifact.
        value: ${{ jobs.attest-sbom-high-perms.outputs.sbom-artifact-id }}
      attest-dependency-scan-attestation-artifact-id:
        description: The artifact-id of the dependency scan attestation artifact.
        value: ${{ jobs.attest-dependency-scan-high-perms.outputs.dependency-scan-artifact-id }}

permissions: {}

env:
  GH_TOKEN: ${{ inputs.github-token || github.token }}
  ARTIFACTS_FOLDER: ./artifacts
  ATTESTATIONS_FOLDER: ./attestations
  POLICY_REF: https://github.com/liatrio/liatrio-rego-policy-library

jobs:
  build-high-perms:
    permissions:
      contents: read
      packages: write
    runs-on: ${{ inputs.workflow-runner-label }}
    outputs:
      image-digest: ${{ steps.build-image.outputs.image-digest }}
      subject-name-sanitized: ${{ steps.sanitize.outputs.name }}
    steps:
      - name: Fail if Runner is self-hosted
        if: ${{ runner.environment != 'github-hosted' }}
        run: |
          echo "Job is running on a self-hosted runner. Terminating job..."
          exit 1
      - name: Sanitize subject name
        id: sanitize
        run: echo "name=$(echo '${{ inputs.subject-name }}' | tr '[:upper:]' '[:lower:]')" >> "$GITHUB_OUTPUT"
      - name: Checkout code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          ref: ${{ github.sha }}
          persist-credentials: false
      - name: Build Image
        if: ${{ runner.environment == 'github-hosted' }}
        id: build-image
        uses: ./.github/actions/build-image
        with:
          subject-name: ${{ inputs.subject-name }}
          registry: ${{ inputs.registry }}

  attest-build-high-perms:
    runs-on: ${{ inputs.workflow-runner-label }}
    needs: build-high-perms
    permissions:
      actions: read
      id-token: write
      attestations: write
      packages: write
      artifact-metadata: write
    outputs:
      provenance-artifact-id: ${{ steps.upload-provenance.outputs.artifact-id }}
    steps:
      - name: Fail if Runner is self-hosted
        if: ${{ runner.environment != 'github-hosted' }}
        run: |
          echo "Job is running on a self-hosted runner. Terminating job..."
          exit 1
      - name: Login to GitHub Container Registry
        if: ${{ runner.environment == 'github-hosted' }}
        uses: docker/login-action@c94ce9fb468520275223c153574b00df6fe4bcc9 # v3.7.0
        with:
          registry: ${{ inputs.registry }}
          username: ${{ github.actor }}
          password: ${{ inputs.github-token || github.token }}
      - name: Attest Provenance
        id: attest-build-provenance
        uses: actions/attest-build-provenance@a2bbfa25375fe432b6a289bc6b6cd05ecd0c4c32 # v4.1.0
        with:
          subject-name: ${{ format('{0}/{1}', inputs.registry, inputs.subject-name) }}
          subject-digest: ${{ needs.build-high-perms.outputs.image-digest }}
          github-token: ${{ inputs.github-token || github.token }}
          push-to-registry: true
      - name: Rename Provenance Bundle
        run: |
          mkdir ${{ env.ATTESTATIONS_FOLDER }}
          mv ${{ steps.attest-build-provenance.outputs.bundle-path }} ${{ env.ATTESTATIONS_FOLDER }}/attest-build-provenance-attestation.jsonl
      - name: Upload Provenance Sigstore Bundle
        id: upload-provenance
        uses: actions/upload-artifact@bbbca2ddaa5d8feaa63e36b76fdaad77386f024f # v7.0.0
        with:
          name: image-build-provenance-attestation-high-perms
          path: ${{ env.ATTESTATIONS_FOLDER }}/attest-build-provenance-attestation.jsonl
          if-no-files-found: error

  attest-metadata-high-perms:
    runs-on: ${{ inputs.workflow-runner-label }}
    needs: build-high-perms
    permissions:
      actions: read
      contents: read
      id-token: write
      attestations: write
      packages: write
      artifact-metadata: write
    outputs:
      metadata-artifact-id: ${{ steps.upload-metadata.outputs.artifact-id }}
    steps:
      - name: Fail if Runner is self-hosted
        if: ${{ runner.environment != 'github-hosted' }}
        run: |
          echo "Job is running on a self-hosted runner. Terminating job..."
          exit 1
      - name: Login to GitHub Container Registry
        if: ${{ runner.environment == 'github-hosted' }}
        uses: docker/login-action@c94ce9fb468520275223c153574b00df6fe4bcc9 # v3.7.0
        with:
          registry: ${{ inputs.registry }}
          username: ${{ github.actor }}
          password: ${{ inputs.github-token || github.token }}
      - uses: octo-sts/action@f603d3be9d8dd9871a265776e625a27b00effe05 # v1.1.1
        id: octo-sts
        with:
          scope: liatrio
          identity: autogov-infra
      - name: Install autogov
        env:
          GH_TOKEN: ${{ steps.octo-sts.outputs.token }}
        run: |
          gh release download ${{ inputs.autogov-version }} \
            --repo liatrio/autogov \
            --pattern "autogov"
          chmod +x autogov
      - name: Generate Metadata Attestation
        env:
          GITHUB_WORKFLOW_INPUTS: ${{ toJson(inputs) }}
        run: |
          set +x
          ./autogov predicate metadata \
            --output metadata.json \
            --type image \
            --subject-name "${{ format('{0}/{1}', inputs.registry, inputs.subject-name) }}" \
            --subject-digest "${{ needs.build-high-perms.outputs.image-digest }}"
          cat metadata.json
      - name: Attest Metadata
        uses: actions/attest@59d89421af93a897026c735860bf21b6eb4f7b26 # v4.1.0
        id: attest-metadata
        with:
          subject-name: ${{ format('{0}/{1}', inputs.registry, inputs.subject-name) }}
          subject-digest: ${{ needs.build-high-perms.outputs.image-digest }}
          predicate-type: 'https://autogov.dev/attestation/metadata/v1'
          predicate-path: metadata.json
          push-to-registry: true
      - name: Rename Metadata Bundle
        run: |
          mkdir ${{ env.ATTESTATIONS_FOLDER }}
          mv ${{ steps.attest-metadata.outputs.bundle-path }} ${{ env.ATTESTATIONS_FOLDER }}/attest-metadata-attestation.jsonl
      - name: Upload Metadata Sigstore Bundle
        uses: actions/upload-artifact@bbbca2ddaa5d8feaa63e36b76fdaad77386f024f # v7.0.0
        id: upload-metadata
        with:
          name: image-metadata-attestation-high-perms
          path: ${{ env.ATTESTATIONS_FOLDER }}/attest-metadata-attestation.jsonl
          if-no-files-found: error

  attest-sbom-high-perms:
    runs-on: ${{ inputs.workflow-runner-label }}
    needs: build-high-perms
    permissions:
      actions: read
      id-token: write
      attestations: write
      contents: read
      packages: write
      artifact-metadata: write
    outputs:
      sbom-artifact-id: ${{ steps.upload-sbom.outputs.artifact-id }}
    steps:
      - name: Fail if Runner is self-hosted
        if: ${{ runner.environment != 'github-hosted' }}
        run: |
          echo "Job is running on a self-hosted runner. Terminating job..."
          exit 1
      - name: Login to GitHub Container Registry
        if: ${{ runner.environment == 'github-hosted' }}
        uses: docker/login-action@c94ce9fb468520275223c153574b00df6fe4bcc9 # v3.7.0
        with:
          registry: ${{ inputs.registry }}
          username: ${{ github.actor }}
          password: ${{ inputs.github-token || github.token }}
      - name: Generate SBOM
        uses: anchore/sbom-action@17ae1740179002c89186b61233e0f892c3118b11 # v0.23.0
        with:
          image: ${{ format('{0}/{1}@{2}', inputs.registry, needs.build-high-perms.outputs.subject-name-sanitized, needs.build-high-perms.outputs.image-digest) }}
          format: cyclonedx-json
          output-file: sbom.cyclonedx.json
          upload-release-assets: false
          upload-artifact: false
          github-token: ${{ inputs.github-token || github.token }}
      - name: Log SBOM File
        run: cat sbom.cyclonedx.json | jq -r
      - name: Generate SBOM attestation
        id: attest-sbom
        uses: actions/attest-sbom@07e74fc4e78d1aad915e867f9a094073a9f71527 # v4.0.0
        with:
          subject-name: ${{ format('{0}/{1}', inputs.registry, inputs.subject-name) }}
          subject-digest: ${{ needs.build-high-perms.outputs.image-digest }}
          sbom-path: sbom.cyclonedx.json
          github-token: ${{ inputs.github-token || github.token }}
          push-to-registry: true
      - name: Rename SBOM Bundle
        run: |
          mkdir ${{ env.ATTESTATIONS_FOLDER }}
          mv ${{ steps.attest-sbom.outputs.bundle-path }} ${{ env.ATTESTATIONS_FOLDER }}/attest-sbom-attestation.jsonl
      - name: Upload SBOM Attestation
        id: upload-sbom
        uses: actions/upload-artifact@bbbca2ddaa5d8feaa63e36b76fdaad77386f024f # v7.0.0
        with:
          name: image-sbom-attestation-high-perms
          path: ${{ env.ATTESTATIONS_FOLDER }}/attest-sbom-attestation.jsonl
          if-no-files-found: error

  attest-dependency-scan-high-perms:
    runs-on: ${{ inputs.workflow-runner-label }}
    needs: build-high-perms
    permissions:
      actions: read
      id-token: write
      attestations: write
      packages: write
      contents: read
      artifact-metadata: write
    outputs:
      dependency-scan-artifact-id: ${{ steps.upload-dependency-scan.outputs.artifact-id }}
    steps:
      - name: Fail if Runner is self-hosted
        if: ${{ runner.environment != 'github-hosted' }}
        run: |
          echo "Job is running on a self-hosted runner. Terminating job..."
          exit 1
      - name: Login to GitHub Container Registry
        if: ${{ runner.environment == 'github-hosted' }}
        uses: docker/login-action@c94ce9fb468520275223c153574b00df6fe4bcc9 # v3.7.0
        with:
          registry: ${{ inputs.registry }}
          username: ${{ github.actor }}
          password: ${{ inputs.github-token || github.token }}
      - uses: octo-sts/action@f603d3be9d8dd9871a265776e625a27b00effe05 # v1.1.1
        id: octo-sts
        with:
          scope: liatrio
          identity: autogov-infra
      - name: Install autogov
        env:
          GH_TOKEN: ${{ steps.octo-sts.outputs.token }}
        run: |
          gh release download ${{ inputs.autogov-version }} \
            --repo liatrio/autogov \
            --pattern "autogov"
          chmod +x autogov
      - name: Scan current project
        uses: anchore/scan-action@7037fa011853d5a11690026fb85feee79f4c946c # v7.3.2
        id: anchore-scan
        with:
          image: ${{ format('{0}/{1}@{2}', inputs.registry, needs.build-high-perms.outputs.subject-name-sanitized, needs.build-high-perms.outputs.image-digest) }}
          output-format: json
          output-file: results.json
          fail-build: false
      - name: Generate Dependency Scan Attestation
        run: |
          set +x
          ./autogov predicate depscan \
            --results-path results.json \
            --subject-name "${{ format('{0}/{1}', inputs.registry, inputs.subject-name) }}" \
            --subject-digest "${{ needs.build-high-perms.outputs.image-digest }}" \
            --output depscan.json
          cat depscan.json
      - name: Attest Dependency Scan
        uses: actions/attest@59d89421af93a897026c735860bf21b6eb4f7b26 # v4.1.0
        id: attest-dep-scan
        with:
          subject-name: ${{ format('{0}/{1}', inputs.registry, inputs.subject-name) }}
          subject-digest: ${{ needs.build-high-perms.outputs.image-digest }}
          predicate-type: 'https://in-toto.io/attestation/vulns/v0.2'
          predicate-path: depscan.json
          push-to-registry: true
      - name: Rename Dependency Scan Bundle
        run: |
          mkdir ${{ env.ATTESTATIONS_FOLDER }}
          mv ${{ steps.attest-dep-scan.outputs.bundle-path }} ${{ env.ATTESTATIONS_FOLDER }}/attest-dep-scan-attestation.jsonl
      - name: Upload Dependency Scan Sigstore Bundle
        uses: actions/upload-artifact@bbbca2ddaa5d8feaa63e36b76fdaad77386f024f # v7.0.0
        id: upload-dependency-scan
        with:
          name: image-dep-scan-attestation-high-perms
          path: ${{ env.ATTESTATIONS_FOLDER }}/attest-dep-scan-attestation.jsonl
          if-no-files-found: error
