name: Build Image High Permissions Reusable Workflow

on:
  workflow_call:
    inputs:
      subject-name:
        description: >
          Subject name as it should appear in the attestation. Required unless
          "subject-path" is specified, in which case it will be inferred from the
          path.
        required: true
        type: string
      registry:
        description: Container registry to push image.
        default: ghcr.io
        required: true
        type: string
      cert-identity:
        description: >
          The certificate identity of the signer workflow, or builder, used in the verify job to ensure artifacts and attestations can be verified against the source repository and correct workflow using the gh-cli (e.g. --cert-identity flag). If verifying an image, the workflow name should be rw-<permissions_path>-attest-image.yaml, if verifying blob(s), the workflow name should be rw-<permissions_path>-attest-blob.yaml.
        required: true
        type: string
      autogov-verify-version:
        description: The autogov-verify version to use.
        required: false
        type: string
        default: v0.8.1
      autogov-helper-version:
        description: The autogov-helper version to use.
        required: false
        type: string
        default: v0.4.3
      release-image:
        description: Whether or not to run the release-image job.
        required: false
        type: boolean
        default: true
    outputs:
      attest-build-attestation-artifact-id:
        description: "Attestation artifact ID"
        value: ${{ jobs.attest-image.outputs.attest-build-attestation-artifact-id }}
      attest-metadata-attestation-artifact-id:
        description: "Metadata artifact ID" 
        value: ${{ jobs.attest-image.outputs.attest-metadata-attestation-artifact-id }}
      attest-sbom-attestation-artifact-id:
        description: "SBOM artifact ID"  
        value: ${{ jobs.attest-image.outputs.attest-sbom-attestation-artifact-id }}
      attest-dependency-scan-attestation-artifact-id: 
        description: "Dependency scan artifact ID" 
        value: ${{ jobs.attest-image.outputs.attest-dependency-scan-attestation-artifact-id }}
      image-digest: 
        description: "image-digest"
        value: ${{ jobs.attest-image.outputs.image-digest }}
      vsa-artifact-id: 
        description: "VSA artifact ID"
        value: ${{ jobs.verify-image.outputs.vsa-artifact-id }}

permissions: {}

jobs:
  attest-image: #image
    permissions:
      id-token: write
      attestations: write
      packages: write
      contents: read
      actions: read
    uses: ./.github/workflows/rw-hp-attest-image.yaml
    secrets: inherit
    with:
      subject-name: ${{ github.repository }}
      registry: ${{ inputs.registry }}
      autogov-helper-version: ${{ inputs.autogov-helper-version }}

  verify-image: #image
    permissions:
      id-token: write
      attestations: write
      packages: write
      contents: read
      actions: read
    needs: [attest-image]
    uses: ./.github/workflows/rw-hp-verify.yaml
    secrets: inherit
    with:
      build-type: image
      subject-name: ${{ inputs.subject-name }}
      image-digest: ${{ needs.attest-image.outputs.image-digest }}
      registry: ${{ inputs.registry }}
      cert-identity: ${{ inputs.cert-identity }}
      autogov-verify-version: ${{ inputs.autogov-verify-version }}

  release-image: #image
    permissions:
      contents: write
      id-token: write
      actions: read
    needs: [verify-image, attest-image]
    if: ${{ inputs.release-image }}
    uses: ./.github/workflows/rw-hp-release.yaml
    secrets: inherit
    with:
      build-type: image
      image-digest: ${{ needs.attest-image.outputs.image-digest }}
      attest-build-attestation-artifact-id: ${{ needs.attest-image.outputs.attest-build-attestation-artifact-id }}
      attest-metadata-attestation-artifact-id: ${{ needs.attest-image.outputs.attest-metadata-attestation-artifact-id }}
      attest-sbom-attestation-artifact-id: ${{ needs.attest-image.outputs.attest-sbom-attestation-artifact-id }}
      attest-dependency-scan-attestation-artifact-id: ${{ needs.attest-image.outputs.attest-dependency-scan-attestation-artifact-id }}
      vsa-artifact-id: ${{ needs.verify-image.outputs.vsa-artifact-id }}
      publish-vsa: true
