name: Release High Permissions Reuseable Workflow

on:
  workflow_call:
    inputs:
      build-type:
        description: 'Specify the type of build: "image" or "blob".'
        required: true
        type: string
      blob-artifact-id:
        type: string
        description: The artifact-id of the build artifacts.
        default: ${{ inputs.build-type == 'blob' && github.event.needs.attest-build.outputs.blob-artifact-id }}
      attest-build-attestation-artifact-id:
        description: The artifact-id of the build provenance attestation artifact.
        default: ${{ github.event.needs.attest-build.outputs.attest-build-attestation-artifact-id }}
        type: string
      attest-metadata-attestation-artifact-id:
        description: The artifact-id of the custom metadata attestation artifact.
        default: ${{ github.event.needs.attest-metadata.outputs.attest-metadata-attestation-artifact-id }}
        type: string
      attest-sbom-attestation-artifact-id:
        description: The artifact-id of the SBOM attestation artifact.
        default: ${{ github.event.needs.attest-sbom.outputs.attest-sbom-attestation-artifact-id }}
        type: string
      attest-dependency-scan-attestation-artifact-id:
        description: The artifact-id of the dependency scan attestation artifact.
        default: ${{ github.event.needs.attest-dependency-scan.outputs.attest-dependency-scan-attestation-artifact-id }}
        type: string
      results-artifact-id:
        type: string
        description: The artifact-id of the results artifact.
        required: true
        default: ${{ github.event.needs.run-opa.outputs.results-artifact-id }}
      workflow-runner-label:
        type: string
        description: The label of the workflow runner
        default: ubuntu-latest
      github-token:
        description: >
          The GitHub token set throughout the reuseable workflow including the composite (build) action.
        required: false
        type: string
      publish-attestations:
        description: Whether to publish attestations as release assets.
        required: false
        type: boolean
        default: true
    outputs:
      semantic-release-version:
        description: The version of the semantic release generated by the semantic-release action.
        value: ${{ jobs.release-high-perms.outputs.semantic-release-version }}

env:
  ARTIFACT_IDS: "${{ inputs.attest-build-attestation-artifact-id }},${{ inputs.attest-metadata-attestation-artifact-id }},${{ inputs.attest-sbom-attestation-artifact-id }},${{ inputs.attest-dependency-scan-attestation-artifact-id }}"
  BLOB_ARTIFACT_ID: ${{ inputs.build-type == 'blob' && inputs.blob-artifact-id || '' }}
  RESULTS_ARTIFACT_ID: ${{ inputs.results-artifact-id }}
  ATTESTATIONS_FOLDER: ./attestations
  ARTIFACTS_FOLDER: ./artifacts
  RESULTS_FOLDER: ./${{ inputs.build-type }}-results

permissions: {}

jobs:
  release-high-perms:
    runs-on: ${{ inputs.workflow-runner-label }}
    if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
    permissions:
      contents: write
      id-token: write
      actions: read
    outputs:
      semantic-release-version: ${{ steps.semantic-release.outputs.new_release_version }}
    steps:
      - name: Fail if Runner is self-hosted
        if: ${{ runner.environment != 'github-hosted' }}
        run: |
          echo "Job is running on a self-hosted runner. Terminating job..."
          exit 1
      - name: Checkout code
        if: ${{ runner.environment == 'github-hosted'}}
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          ref: ${{ github.sha }}
          persist-credentials: false
      - name: Create Artifacts Folder
        if: ${{ inputs.build-type == 'blob' }}
        run: mkdir ${{ env.ARTIFACTS_FOLDER }}
      - name: Download Blob Artifact(s)
        if: ${{ inputs.build-type == 'blob' }}
        uses: actions/download-artifact@d3f86a106a0bac45b974a628896c90dbdf5c8093 # v4.3.0
        with:
          github-token: ${{ inputs.github-token || github.token }}
          artifact-ids: ${{ env.BLOB_ARTIFACT_ID }}
          path: ${{ env.ARTIFACTS_FOLDER }}
          merge-multiple: true
      - name: Create Attestations Folder
        run: mkdir ${{ env.ATTESTATIONS_FOLDER }}
      - name: Download Sigstore Bundle(s)
        uses: actions/download-artifact@d3f86a106a0bac45b974a628896c90dbdf5c8093 # v4.3.0
        with:
          github-token: ${{ inputs.github-token || github.token }}
          artifact-ids: ${{ env.ARTIFACT_IDS }}
          path: ${{ env.ATTESTATIONS_FOLDER }}
          merge-multiple: true
      - name: Download opa-run Results
        uses: actions/download-artifact@d3f86a106a0bac45b974a628896c90dbdf5c8093 # v4.3.0
        with:
          github-token: ${{ inputs.github-token || github.token }}
          artifact-ids: ${{ env.RESULTS_ARTIFACT_ID }}
          path: ${{ env.RESULTS_FOLDER }}
          merge-multiple: true
      - uses: octo-sts/action@6177b4481c00308b3839969c3eca88c96a91775f # v1.0.0
        id: octo-sts
        with:
          scope: ${{ github.repository }}
          identity: release-ops
      - name: Run semantic-release
        uses: cycjimmy/semantic-release-action@16ca923e6ccbb50770c415a0ccd43709a8c5f7a4 # v4.2.2
        id: semantic-release
        with:
          extra_plugins: |
            @semantic-release/commit-analyzer
            @semantic-release/release-notes-generator
            @semantic-release/exec
            @semantic-release-extras/verified-git-commit
            @semantic-release/github
            conventional-changelog-conventionalcommits
        env:
          GITHUB_TOKEN: ${{ steps.octo-sts.outputs.token }}
      - name: Upload Results/Sigstore Bundle as Release Asset
        if: steps.semantic-release.outputs.new_release_published == 'true'
        uses: softprops/action-gh-release@c95fe1489396fe8a9eb87c0abf8aa5b2ef267fda # v2.2.1
        with:
          files: |
            ${{ env.RESULTS_FOLDER }}/results-*
            ${{ inputs.publish-attestations && format('{0}/*', env.ATTESTATIONS_FOLDER) || '' }}
            ${{ inputs.build-type == 'blob' && env.BLOB_ARTIFACT_ID && format('{0}/*', env.ARTIFACTS_FOLDER) || '' }}
          tag_name: v${{ steps.semantic-release.outputs.new_release_version }}
          token: ${{ inputs.github-token || github.token }}
