name: Release High Permissions Reuseable Workflow

on:
  workflow_call:
    inputs:
      build-type:
        description: 'Specify the type of build: "image" or "blob".'
        required: true
        type: string
      blob-artifact-id:
        type: string
        description: The artifact-id of the build artifacts.
        default: ${{ inputs.build-type == 'blob' && github.event.needs.attest-build.outputs.blob-artifact-id }}
      attest-build-attestation-artifact-id:
        description: The artifact-id of the build provenance attestation artifact.
        default: ${{ github.event.needs.attest-build.outputs.attest-build-attestation-artifact-id }}
        type: string
      attest-metadata-attestation-artifact-id:
        description: The artifact-id of the custom metadata attestation artifact.
        default: ${{ github.event.needs.attest-metadata.outputs.attest-metadata-attestation-artifact-id }}
        type: string
      attest-sbom-attestation-artifact-id:
        description: The artifact-id of the SBOM attestation artifact.
        default: ${{ github.event.needs.attest-sbom.outputs.attest-sbom-attestation-artifact-id }}
        type: string
      attest-dependency-scan-attestation-artifact-id:
        description: The artifact-id of the dependency scan attestation artifact.
        default: ${{ github.event.needs.attest-dependency-scan.outputs.attest-dependency-scan-attestation-artifact-id }}
        type: string
      results-artifact-id:
        type: string
        description: The artifact-id of the results artifact.
        required: false
        default: ${{ github.event.needs.run-opa.outputs.results-artifact-id }}
      workflow-runner-label:
        type: string
        description: The label of the workflow runner
        default: ubuntu-latest
      github-token:
        description: >
          The GitHub token set throughout the reuseable workflow including the composite (build) action.
        required: false
        type: string
      publish-attestations:
        description: Whether to publish attestations as release assets.
        required: false
        type: boolean
        default: true
      image-digest:
        description: The digest of the built image.
        required: false
        type: string
    outputs:
      release-version:
        description: The version of the release generated by release-please.
        value: ${{ jobs.release-high-perms.outputs.release-version }}

env:
  ARTIFACT_IDS: "${{ inputs.attest-build-attestation-artifact-id }},${{ inputs.attest-metadata-attestation-artifact-id }},${{ inputs.attest-sbom-attestation-artifact-id }},${{ inputs.attest-dependency-scan-attestation-artifact-id }}"
  BLOB_ARTIFACT_ID: ${{ inputs.build-type == 'blob' && inputs.blob-artifact-id || '' }}
  RESULTS_ARTIFACT_ID: ${{ inputs.results-artifact-id || '' }}
  ATTESTATIONS_FOLDER: ./attestations
  ARTIFACTS_FOLDER: ./artifacts
  RESULTS_FOLDER: ./${{ inputs.build-type }}-results

permissions: {}

jobs:
  release-high-perms:
    runs-on: ${{ inputs.workflow-runner-label }}
    if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
    permissions:
      contents: write
      id-token: write
      actions: read
      pull-requests: write
    outputs:
      release-version: ${{ steps.release-please.outputs.tag_name }}
    steps:
      - name: Fail if Runner is self-hosted
        if: ${{ runner.environment != 'github-hosted' }}
        run: |
          echo "Job is running on a self-hosted runner. Terminating job..."
          exit 1
      - name: Checkout code
        if: ${{ runner.environment == 'github-hosted'}}
        uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4.3.0
        with:
          ref: ${{ github.sha }}
          persist-credentials: false
      - name: Create Release
        uses: softprops/action-gh-release@72f2c25fcb47643c292f7107632f7a47c1df5cd8 # v2.3.2
        with:
          draft: true
      - name: Create Artifacts Folder
        if: ${{ inputs.build-type == 'blob' }}
        run: mkdir ${{ env.ARTIFACTS_FOLDER }}
      - name: Download Blob Artifact(s)
        if: ${{ inputs.build-type == 'blob' }}
        uses: actions/download-artifact@d3f86a106a0bac45b974a628896c90dbdf5c8093 # v4.3.0
        with:
          github-token: ${{ inputs.github-token || github.token }}
          artifact-ids: ${{ env.BLOB_ARTIFACT_ID }}
          path: ${{ env.ARTIFACTS_FOLDER }}
          merge-multiple: true
      - name: Create Attestations Folder
        run: mkdir ${{ env.ATTESTATIONS_FOLDER }}
      - name: Download Sigstore Bundle(s)
        uses: actions/download-artifact@d3f86a106a0bac45b974a628896c90dbdf5c8093 # v4.3.0
        with:
          github-token: ${{ inputs.github-token || github.token }}
          artifact-ids: ${{ env.ARTIFACT_IDS }}
          path: ${{ env.ATTESTATIONS_FOLDER }}
          merge-multiple: true
      - name: Download opa-run Results
        if: ${{ env.RESULTS_ARTIFACT_ID != '' }}
        uses: actions/download-artifact@d3f86a106a0bac45b974a628896c90dbdf5c8093 # v4.3.0
        with:
          github-token: ${{ inputs.github-token || github.token }}
          artifact-ids: ${{ env.RESULTS_ARTIFACT_ID }}
          path: ${{ env.RESULTS_FOLDER }}
          merge-multiple: true
      - uses: octo-sts/action@6177b4481c00308b3839969c3eca88c96a91775f # v1.0.0
        id: octo-sts
        with:
          scope: ${{ github.repository }}
          identity: release-ops
      - name: Create Release
        uses: googleapis/release-please-action@7987652d64b4581673a76e33ad5e98e3dd56832f # v4.1.3
        id: release-please
        with:
          token: ${{ steps.octo-sts.outputs.token }}
          config-file: release-please-config.json
          manifest-file: .release-please-manifest.json
      - name: Upload Release Assets
        if: ${{ steps.release-please.outputs.release_created }}
        env:
          GITHUB_TOKEN: ${{ steps.octo-sts.outputs.token }}
        run: |
          # upload release assets
          # results files if they exist
          if [ "${{ env.RESULTS_ARTIFACT_ID }}" != "" ] && [ -d "${{ env.RESULTS_FOLDER }}" ]; then
            find "${{ env.RESULTS_FOLDER }}" -name "results-*" -type f -exec gh release upload "${{ steps.release-please.outputs.tag_name }}" {} \;
          fi

          # attestation files if enabled
          if [ "${{ inputs.publish-attestations }}" = "true" ] && [ -d "${{ env.ATTESTATIONS_FOLDER }}" ]; then
            find "${{ env.ATTESTATIONS_FOLDER }}" -type f -exec gh release upload "${{ steps.release-please.outputs.tag_name }}" {} \;
          fi

          # artifact files for blob builds
          if [ "${{ inputs.build-type }}" = "blob" ] && [ "${{ env.BLOB_ARTIFACT_ID }}" != "" ] && [ -d "${{ env.ARTIFACTS_FOLDER }}" ]; then
            find "${{ env.ARTIFACTS_FOLDER }}" -type f -exec gh release upload "${{ steps.release-please.outputs.tag_name }}" {} \;
          fi
