name: Attest Image High Permissions Reusable Workflow

on:
  workflow_call:
    inputs:
      subject-name:
        description: >
          Subject name as it should appear in the attestation. Required unless
          "subject-path" is specified, in which case it will be inferred from the
          path.
        required: true
        type: string
      registry:
        description: Container registry to push image.
        default: ghcr.io
        required: true
        type: string
      show-summary:
        description: >
          Whether to attach a list of generated attestations to the workflow run
          summary page. Defaults to true.
        default: true
        required: false
        type: boolean
      workflow-runner-label:
        description: >
          The label used for runner/OS selection, examples:
          https://docs.github.com/en/actions/writing-workflows/choosing-where-your-workflow-runs/choosing-the-runner-for-a-job#example-specifying-an-operating-system.
        default: ubuntu-latest
        required: false
        type: string
      github-token:
        description: >
          The GitHub token set throughout the reusable workflow including the composite (build) action.
        required: false
        type: string
      autogov-helper-version:
        description: The autogov-helper version to use.
        required: false
        type: string
        default: v0.4.3
    outputs:
      image-digest:
        description: The image digest of the image that was built from the build-image job.
        value: ${{ jobs.build-high-perms.outputs.image-digest }}
      attest-build-attestation-artifact-id:
        description: The artifact-id of the build provenance attestation artifact.
        value: ${{ jobs.attest-build-high-perms.outputs.provenance-artifact-id }}
      attest-metadata-attestation-artifact-id:
        description: The artifact-id of the custom metadata attestation artifact.
        value: ${{ jobs.attest-metadata-high-perms.outputs.metadata-artifact-id }}
      attest-sbom-attestation-artifact-id:
        description: The artifact-id of the SBOM attestation artifact.
        value: ${{ jobs.attest-sbom-high-perms.outputs.sbom-artifact-id }}
      attest-dependency-scan-attestation-artifact-id:
        description: The artifact-id of the dependency scan attestation artifact.
        value: ${{ jobs.attest-dependency-scan-high-perms.outputs.dependency-scan-artifact-id }}

permissions: {}

env:
  GH_TOKEN: ${{ inputs.github-token || github.token }}
  ARTIFACTS_FOLDER: ./artifacts
  ATTESTATIONS_FOLDER: ./attestations
  POLICY_REF: https://github.com/liatrio/liatrio-rego-policy-library
  OTEL_EXPORTER_OTLP_ENDPOINT: o11y-gh-traces-grpc-receiver.dev.k8s-platform-v3.liatr.io:443
  OTEL_EXPORTER_OTLP_PROTOCOL: grpc
  OTEL_EXPORTER_OTLP_HEADERS: ""
  OTEL_SERVICE_NAME: ${{ github.event.repository.name }}

jobs:
  build-high-perms:
    permissions:
      contents: read
      packages: write
    runs-on: ${{ inputs.workflow-runner-label }}
    outputs:
      image-digest: ${{ steps.build-image.outputs.image-digest }}
    steps:
      - name: Fail if Runner is self-hosted
        if: ${{ runner.environment != 'github-hosted' }}
        run: |
          echo "Job is running on a self-hosted runner. Terminating job..."
          exit 1
      - name: Checkout code
        uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5.0.1
        with:
          ref: ${{ github.sha }}
          persist-credentials: false
      - name: Build Image
        if: ${{ runner.environment == 'github-hosted' }}
        id: build-image
        uses: ./.github/actions/build-image
        with:
          subject-name: ${{ inputs.subject-name }}
          registry: ${{ inputs.registry }}

  attest-build-high-perms:
    runs-on: ${{ inputs.workflow-runner-label }}
    needs: build-high-perms
    permissions:
      actions: read
      id-token: write
      attestations: write
      packages: write
    outputs:
      provenance-artifact-id: ${{ steps.upload-provenance.outputs.artifact-id }}
    steps:
      - name: Fail if Runner is self-hosted
        if: ${{ runner.environment != 'github-hosted' }}
        run: |
          echo "Job is running on a self-hosted runner. Terminating job..."
          exit 1
      - name: Login to GitHub Container Registry
        if: ${{ runner.environment == 'github-hosted' }}
        uses: docker/login-action@5e57cd118135c172c3672efd75eb46360885c0ef # v3.6.0
        with:
          registry: ${{ inputs.registry }}
          username: ${{ github.actor }}
          password: ${{ inputs.github-token || github.token }}
      - uses: octo-sts/action@d6c70ad3b9ac85df6da6b9749014d7283987cfec # v1.0.3
        id: octo-sts
        with:
          scope: liatrio
          identity: autogov-infra
      - name: Install autogov-helper
        run: |
          set +x
          export GH_TOKEN=${{ steps.octo-sts.outputs.token }}
          gh release download ${{ inputs.autogov-helper-version }} \
            --repo liatrio/autogov-helper \
            --pattern "autogov-helper"
          chmod +x autogov-helper
      - name: Attest Provenance
        id: attest-build-provenance
        uses: actions/attest-build-provenance@977bb373ede98d70efdf65b84cb5f73e068dcc2a # v3.0.0
        with:
          subject-name: ${{ format('{0}/{1}', inputs.registry, inputs.subject-name) }}
          subject-digest: ${{ needs.build-high-perms.outputs.image-digest }}
          github-token: ${{ inputs.github-token || github.token }}
          push-to-registry: true
      - name: Rename Provenance Bundle
        run: |
          mkdir ${{ env.ATTESTATIONS_FOLDER }}
          mv ${{ steps.attest-build-provenance.outputs.bundle-path }} ${{ env.ATTESTATIONS_FOLDER }}/attest-build-provenance-attestation.jsonl
      - name: Emit Provenance Attestation Content
        uses: liatrio/run-with-telemetry@17cf80578d78573a8895cdbc9a4c2a1fbb707788 # latest
        with:
          otel-exporter-otlp-endpoint: ${{ env.OTEL_EXPORTER_OTLP_ENDPOINT }}
          otel-service-name: ${{ env.OTEL_SERVICE_NAME }}
          github-token: ${{ inputs.github-token || github.token }}
          step-name: Emit Provenance Attestation Content
          run: |
            set +x
            export OTEL_EXPORTER_OTLP_ENDPOINT=https://${{ env.OTEL_EXPORTER_OTLP_ENDPOINT }}
            ./autogov-helper att-span --bundle-path ${{ env.ATTESTATIONS_FOLDER }}/attest-build-provenance-attestation.jsonl
      - name: Upload Provenance Sigstore Bundle
        id: upload-provenance
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
        with:
          name: image-build-provenance-attestation-high-perms
          path: ${{ env.ATTESTATIONS_FOLDER }}/attest-build-provenance-attestation.jsonl
          if-no-files-found: error

  attest-metadata-high-perms:
    runs-on: ${{ inputs.workflow-runner-label }}
    needs: build-high-perms
    permissions:
      actions: read
      contents: read
      id-token: write
      attestations: write
      packages: write
    outputs:
      metadata-artifact-id: ${{ steps.upload-metadata.outputs.artifact-id }}
    steps:
      - name: Fail if Runner is self-hosted
        if: ${{ runner.environment != 'github-hosted' }}
        run: |
          echo "Job is running on a self-hosted runner. Terminating job..."
          exit 1
      - name: Login to GitHub Container Registry
        if: ${{ runner.environment == 'github-hosted' }}
        uses: docker/login-action@5e57cd118135c172c3672efd75eb46360885c0ef # v3.6.0
        with:
          registry: ${{ inputs.registry }}
          username: ${{ github.actor }}
          password: ${{ inputs.github-token || github.token }}
      - uses: octo-sts/action@d6c70ad3b9ac85df6da6b9749014d7283987cfec # v1.0.3
        id: octo-sts
        with:
          scope: liatrio
          identity: autogov-infra
      - name: Install autogov-helper
        run: |
          set +x
          export GH_TOKEN=${{ steps.octo-sts.outputs.token }}
          gh release download ${{ inputs.autogov-helper-version }} \
            --repo liatrio/autogov-helper \
            --pattern "autogov-helper"
          chmod +x autogov-helper
      - name: Generate Metadata Attestation
        env:
          GITHUB_WORKFLOW_INPUTS: ${{ toJson(inputs) }}
        run: |
          set +x
          ./autogov-helper metadata \
            --output metadata.json \
            --type image \
            --subject-name "${{ format('{0}/{1}', inputs.registry, inputs.subject-name) }}" \
            --subject-digest "${{ needs.build-high-perms.outputs.image-digest }}"
          cat metadata.json
      - name: Attest Metadata
        uses: actions/attest@daf44fb950173508f38bd2406030372c1d1162b1 # v3.0.0
        id: attest-metadata
        with:
          subject-name: ${{ format('{0}/{1}', inputs.registry, inputs.subject-name) }}
          subject-digest: ${{ needs.build-high-perms.outputs.image-digest }}
          predicate-type: 'https://autogov.dev/attestation/metadata/v1'
          predicate-path: metadata.json
          push-to-registry: true
      - name: Rename Metadata Bundle
        run: |
          mkdir ${{ env.ATTESTATIONS_FOLDER }}
          mv ${{ steps.attest-metadata.outputs.bundle-path }} ${{ env.ATTESTATIONS_FOLDER }}/attest-metadata-attestation.jsonl
      - name: Emit Metadata Attestation Content
        uses: liatrio/run-with-telemetry@17cf80578d78573a8895cdbc9a4c2a1fbb707788 # latest
        with:
          otel-exporter-otlp-endpoint: ${{ env.OTEL_EXPORTER_OTLP_ENDPOINT }}
          otel-service-name: ${{ env.OTEL_SERVICE_NAME }}
          github-token: ${{ inputs.github-token || github.token }}
          step-name: Emit Metadata Attestation Content
          run: |
            set +x
            export OTEL_EXPORTER_OTLP_ENDPOINT=https://${{ env.OTEL_EXPORTER_OTLP_ENDPOINT }}
            ./autogov-helper att-span --bundle-path ${{ env.ATTESTATIONS_FOLDER }}/attest-metadata-attestation.jsonl
      - name: Upload Metadata Sigstore Bundle
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
        id: upload-metadata
        with:
          name: image-metadata-attestation-high-perms
          path: ${{ env.ATTESTATIONS_FOLDER }}/attest-metadata-attestation.jsonl
          if-no-files-found: error

  attest-sbom-high-perms:
    runs-on: ${{ inputs.workflow-runner-label }}
    needs: build-high-perms
    permissions:
      actions: read
      id-token: write
      attestations: write
      contents: read
      packages: write
    outputs:
      sbom-artifact-id: ${{ steps.upload-sbom.outputs.artifact-id }}
    steps:
      - name: Fail if Runner is self-hosted
        if: ${{ runner.environment != 'github-hosted' }}
        run: |
          echo "Job is running on a self-hosted runner. Terminating job..."
          exit 1
      - name: Login to GitHub Container Registry
        if: ${{ runner.environment == 'github-hosted' }}
        uses: docker/login-action@5e57cd118135c172c3672efd75eb46360885c0ef # v3.6.0
        with:
          registry: ${{ inputs.registry }}
          username: ${{ github.actor }}
          password: ${{ inputs.github-token || github.token }}
      - uses: octo-sts/action@d6c70ad3b9ac85df6da6b9749014d7283987cfec # v1.0.3
        id: octo-sts
        with:
          scope: liatrio
          identity: autogov-infra
      - name: Install autogov-helper
        run: |
          set +x
          export GH_TOKEN=${{ steps.octo-sts.outputs.token }}
          gh release download ${{ inputs.autogov-helper-version }} \
            --repo liatrio/autogov-helper \
            --pattern "autogov-helper"
          chmod +x autogov-helper
      - name: Generate SBOM
        uses: anchore/sbom-action@fbfd9c6c189226748411491745178e0c2017392d # v0.20.10
        with:
          image: ${{ format('{0}/{1}@{2}', inputs.registry, github.repository, needs.build-high-perms.outputs.image-digest) }}
          format: cyclonedx-json
          output-file: sbom.cyclonedx.json
          upload-release-assets: false
          upload-artifact: false
          github-token: ${{ inputs.github-token || github.token }}
      - name: Log SBOM File
        run: cat sbom.cyclonedx.json | jq -r
      - name: Generate SBOM attestation
        id: attest-sbom
        uses: actions/attest-sbom@4651f806c01d8637787e274ac3bdf724ef169f34 # v3.0.0
        with:
          subject-name: ${{ format('{0}/{1}', inputs.registry, inputs.subject-name) }}
          subject-digest: ${{ needs.build-high-perms.outputs.image-digest }}
          sbom-path: sbom.cyclonedx.json
          github-token: ${{ inputs.github-token || github.token }}
          push-to-registry: true
      - name: Rename SBOM Bundle
        run: |
          mkdir ${{ env.ATTESTATIONS_FOLDER }}
          mv ${{ steps.attest-sbom.outputs.bundle-path }} ${{ env.ATTESTATIONS_FOLDER }}/attest-sbom-attestation.jsonl
      - name: Emit SBOM Attestation Content
        uses: liatrio/run-with-telemetry@17cf80578d78573a8895cdbc9a4c2a1fbb707788 # latest
        with:
          otel-exporter-otlp-endpoint: ${{ env.OTEL_EXPORTER_OTLP_ENDPOINT }}
          otel-service-name: ${{ env.OTEL_SERVICE_NAME }}
          github-token: ${{ inputs.github-token || github.token }}
          step-name: Emit SBOM Attestation Content
          run: |
            set +x
            export OTEL_EXPORTER_OTLP_ENDPOINT=https://${{ env.OTEL_EXPORTER_OTLP_ENDPOINT }}
            ./autogov-helper att-span --bundle-path ${{ env.ATTESTATIONS_FOLDER }}/attest-sbom-attestation.jsonl
      - name: Upload SBOM Attestation
        id: upload-sbom
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
        with:
          name: image-sbom-attestation-high-perms
          path: ${{ env.ATTESTATIONS_FOLDER }}/attest-sbom-attestation.jsonl
          if-no-files-found: error

  attest-dependency-scan-high-perms:
    runs-on: ${{ inputs.workflow-runner-label }}
    needs: build-high-perms
    permissions:
      actions: read
      id-token: write
      attestations: write
      packages: write
      contents: read
    outputs:
      dependency-scan-artifact-id: ${{ steps.upload-dependency-scan.outputs.artifact-id }}
    steps:
      - name: Fail if Runner is self-hosted
        if: ${{ runner.environment != 'github-hosted' }}
        run: |
          echo "Job is running on a self-hosted runner. Terminating job..."
          exit 1
      - name: Login to GitHub Container Registry
        if: ${{ runner.environment == 'github-hosted' }}
        uses: docker/login-action@5e57cd118135c172c3672efd75eb46360885c0ef # v3.6.0
        with:
          registry: ${{ inputs.registry }}
          username: ${{ github.actor }}
          password: ${{ inputs.github-token || github.token }}
      - uses: octo-sts/action@d6c70ad3b9ac85df6da6b9749014d7283987cfec # v1.0.3
        id: octo-sts
        with:
          scope: liatrio
          identity: autogov-infra
      - name: Install autogov-helper
        run: |
          set +x
          export GH_TOKEN=${{ steps.octo-sts.outputs.token }}
          gh release download ${{ inputs.autogov-helper-version }} \
            --repo liatrio/autogov-helper \
            --pattern "autogov-helper"
          chmod +x autogov-helper
      - name: Scan current project
        uses: anchore/scan-action@3aaf50d765cfcceafa51d322ccb790e40f6cd8c5 # v7.2.0
        id: anchore-scan
        with:
          image: ${{ format('{0}/{1}@{2}', inputs.registry, github.repository, needs.build-high-perms.outputs.image-digest) }}
          output-format: json
          output-file: results.json
          fail-build: false
      - name: Generate Dependency Scan Attestation
        run: |
          set +x
          ./autogov-helper depscan \
            --results-path results.json \
            --subject-name "${{ format('{0}/{1}', inputs.registry, inputs.subject-name) }}" \
            --digest "${{ needs.build-high-perms.outputs.image-digest }}" \
            --output depscan.json
          cat depscan.json
      - name: Attest Dependency Scan
        uses: actions/attest@daf44fb950173508f38bd2406030372c1d1162b1 # v3.0.0
        id: attest-dep-scan
        with:
          subject-name: ${{ format('{0}/{1}', inputs.registry, inputs.subject-name) }}
          subject-digest: ${{ needs.build-high-perms.outputs.image-digest }}
          predicate-type: 'https://in-toto.io/attestation/vulns/v0.2'
          predicate-path: depscan.json
          push-to-registry: true
      - name: Rename Dependency Scan Bundle
        run: |
          mkdir ${{ env.ATTESTATIONS_FOLDER }}
          mv ${{ steps.attest-dep-scan.outputs.bundle-path }} ${{ env.ATTESTATIONS_FOLDER }}/attest-dep-scan-attestation.jsonl
      - name: Emit Dependency Scan Attestation Content
        uses: liatrio/run-with-telemetry@17cf80578d78573a8895cdbc9a4c2a1fbb707788 # latest
        with:
          otel-exporter-otlp-endpoint: ${{ env.OTEL_EXPORTER_OTLP_ENDPOINT }}
          otel-service-name: ${{ env.OTEL_SERVICE_NAME }}
          github-token: ${{ inputs.github-token || github.token }}
          step-name: Emit Dependency Scan Attestation Content
          run: |
            set +x
            export OTEL_EXPORTER_OTLP_ENDPOINT=https://${{ env.OTEL_EXPORTER_OTLP_ENDPOINT }}
            ./autogov-helper att-span --bundle-path ${{ env.ATTESTATIONS_FOLDER }}/attest-dep-scan-attestation.jsonl
      - name: Upload Dependency Scan Sigstore Bundle
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
        id: upload-dependency-scan
        with:
          name: image-dep-scan-attestation-high-perms
          path: ${{ env.ATTESTATIONS_FOLDER }}/attest-dep-scan-attestation.jsonl
          if-no-files-found: error
