name: Release High Permissions Reuseable Workflow

on:
  workflow_call:
    inputs:
      build-type:
        description: 'Specify the type of build: "image" or "blob".'
        required: true
        type: string
      blob-artifact-id:
        type: string
        description: The artifact-id of the build artifacts.
        default: ${{ inputs.build-type == 'blob' && github.event.needs.attest-build.outputs.blob-artifact-id }}
      attest-build-attestation-artifact-id:
        description: The artifact-id of the build provenance attestation artifact.
        default: ${{ github.event.needs.attest-build.outputs.attest-build-attestation-artifact-id }}
        type: string
      attest-metadata-attestations-artifact-id:
        description: The artifact-id of the custom metadata attestation artifact.
        default: ${{ github.event.needs.attest-metadata.outputs.attest-metadata-attestations-artifact-id }}
        type: string
      attest-sbom-attestations-artifact-id:
        description: The artifact-id of the SBOM attestation artifact.
        default: ${{ github.event.needs.attest-sbom.outputs.attest-sbom-attestations-artifact-id }}
        type: string
      results-artifact-id:
        type: string
        description: The artifact-id of the results artifact.
        required: true
        default: ${{ github.event.needs.run-opa.outputs.results-artifact-id }}
      workflow-runner-label:
        type: string
        description: The label of the workflow runner
        default: ubuntu-latest
      github-token:
        description: >
          The GitHub token set throughout the reuseable workflow including the composite (build) action.
        required: false
        type: string
    outputs:
      semantic-release-version:
        description: The version of the semantic release generated by the go-semantic-release action.
        value: ${{ jobs.release-high-perms.outputs.version }}

env:
  ARTIFACT_IDS: |
    ${{ inputs.attest-build-attestation-artifact-id }}
    ${{ inputs.attest-metadata-attestations-artifact-id }}
    ${{ inputs.attest-sbom-attestations-artifact-id }}
  BLOB_ARTIFACT_ID: ${{ inputs.build-type == 'blob' && inputs.blob-artifact-id || '' }}
  RESULTS_ARTIFACT_ID: ${{ inputs.results-artifact-id }}
  ATTESTATIONS_FOLDER: ./attestations
  ARTIFACTS_FOLDER: ./artifacts
  RESULTS_FOLDER: ./${{ inputs.build-type }}-results

permissions: {}

jobs:
  release-high-perms:
    runs-on: ${{ inputs.workflow-runner-label }}
    if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
    permissions:
      contents: write
      id-token: write
    steps:
      - name: Fail if Runner is self-hosted
        if: ${{ runner.environment != 'github-hosted' }}
        run: |
          echo "Job is running on a self-hosted runner. Terminating job..."
          exit 1
      - name: Install actions/artifact Library
        if: ${{ runner.environment == 'github-hosted'}}
        run: npm install @actions/artifact@2.1.11
      - name: Create Artifacts Folder
        if: ${{ inputs.build-type == 'blob' }}
        run: mkdir ${{ env.ARTIFACTS_FOLDER }}
      - name: Download Blob Artifact(s)
        if: ${{ inputs.build-type == 'blob' }}
        uses: actions/github-script@60a0d83039c74a4aee543508d2ffcb1c3799cdea # v7.0.1
        with:
          script: |
            const { DefaultArtifactClient } = require('@actions/artifact');
            const artifactClient = new DefaultArtifactClient();
            const artifactId = process.env.BLOB_ARTIFACT_ID;

            if (!artifactId) {
              throw new Error('Artifact ID is not defined');
            }

            await artifactClient.downloadArtifact(artifactId, { path: process.env.ARTIFACTS_FOLDER });
            console.log(`Downloaded artifact with ID: ${artifactId} to ${process.env.ARTIFACTS_FOLDER}`);
      - name: Create Attestations Folder
        run: mkdir ${{ env.ATTESTATIONS_FOLDER }}
      - name: Download Sigstore Bundle(s)
        uses: actions/github-script@60a0d83039c74a4aee543508d2ffcb1c3799cdea # v7.0.1
        with:
          script: |
            const { DefaultArtifactClient } = require('@actions/artifact');
            const artifactClient = new DefaultArtifactClient();
            const artifactIds = process.env.ARTIFACT_IDS.split('\n').map(id => id.trim()).filter(id => id);

            for (const artifactId of artifactIds) {
              if (!artifactId) {
                console.log('Skipping undefined artifact ID');
                continue;
              }

              await artifactClient.downloadArtifact(artifactId, { path: process.env.ATTESTATIONS_FOLDER });
              console.log(`Downloaded artifact with ID: ${artifactId} to ${process.env.ATTESTATIONS_FOLDER}`);
            }
      - name: Process Sigstore Bundle(s)
        run: cat ${{ env.ATTESTATIONS_FOLDER }}/*.jsonl > ${{ env.ATTESTATIONS_FOLDER }}/sigstore-bundle.jsonl
      - name: Download opa-run Results
        uses: actions/github-script@60a0d83039c74a4aee543508d2ffcb1c3799cdea # v7.0.1
        with:
          script: |
            const { DefaultArtifactClient } = require('@actions/artifact');
            const artifactClient = new DefaultArtifactClient();
            const artifactId = process.env.RESULTS_ARTIFACT_ID;

            if (!artifactId) {
              throw new Error('Artifact ID is not defined');
            }

            await artifactClient.downloadArtifact(artifactId, { path: process.env.RESULTS_FOLDER });
            console.log(`Downloaded artifact with ID: ${artifactId} to ${process.env.RESULTS_FOLDER}`);
      - name: Check out repository code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - uses: octo-sts/action@6177b4481c00308b3839969c3eca88c96a91775f # v1.0.0
        id: octo-sts
        with:
          scope: ${{ github.repository }}
          identity: main-semantic-release
      - name: Run go-semantic-release
        uses: go-semantic-release/action@48d83acd958dae62e73701aad20a5b5844a3bf45 # v1.23.0
        id: go-semantic-release
        with:
          github-token: ${{ steps.octo-sts.outputs.token }}
          changelog-generator-opt: emojis=true
          allow-initial-development-versions: true
      - name: Upload Results/Sigstore Bundle as Release Asset
        if: steps.go-semantic-release.outputs.version != ''
        uses: softprops/action-gh-release@c95fe1489396fe8a9eb87c0abf8aa5b2ef267fda # v2.2.1
        with:
          files: |
            ${{ env.RESULTS_FOLDER }}/*
            ${{ env.ATTESTATIONS_FOLDER }}/*.jsonl
            ${{ inputs.build-type == 'blob' && env.BLOB_ARTIFACT_ID && format('{0}/*', env.ARTIFACTS_FOLDER) || '' }}
          tag_name: v${{ steps.go-semantic-release.outputs.version }}
          token: ${{ steps.octo-sts.outputs.token }}
