name: Build Image High Permissions Reuseable Workflow

on:
  workflow_call:
    inputs:
      subject-name:
        description: >
          Subject name as it should appear in the attestation. Required unless
          "subject-path" is specified, in which case it will be inferred from the
          path.
        required: true
        type: string
      registry:
        description: Container registry to push image.
        default: ghcr.io
        required: true
        type: string
      cert-identity:
        description: >
          The certificate identity of the signer workflow, or builder, used in the verify job to ensure artifacts and attestations can be verified against the source repository and correct workflow using the gh-cli (e.g. --cert-identity flag). If verifying an image, the workflow name should be rw-<permissions_path>-attest-image.yaml, if verifying blob(s), the workflow name should be rw-<permissions_path>-attest-blob.yaml.
        required: true
        type: string
      ignore-dependency-vulnerabilities:
        description: Whether to ignore dependency vulnerabilities during OPA evaluation.
        required: false
        type: boolean
        # defaults to true in workflows repo, false elsewhere
        default: ${{ github.repository == format('{0}/{1}', github.repository_owner, 'liatrio-gh-autogov-workflows') }}
      autogov-verify-version:
        description: The autogov-verify version to use.
        required: false
        type: string
        default: v0.4.4
      autogov-helper-version:
        description: The autogov-helper version to use.
        required: false
        type: string
        default: v0.4.2
      publish-attestations:
        description: Whether to publish attestations as release assets.
        required: false
        type: boolean
        default: true
      verify-image:
        description: Whether to run the verify-image job.
        required: false
        type: boolean
        default: true
      run-opa-image:
        description: Whether to run the run-opa-image job.
        required: false
        type: boolean
        default: true
      release-image:
        description: Whether to run the release-image job.
        required: false
        type: boolean
        default: true

permissions: {}

jobs:
  attest-image: #image
    permissions:
      id-token: write
      attestations: write
      packages: write
      contents: read
      actions: read
    uses: ./.github/workflows/rw-hp-attest-image.yaml
    secrets: inherit
    with:
      subject-name: ${{ github.repository }}
      registry: ${{ inputs.registry }}
      autogov-helper-version: ${{ inputs.autogov-helper-version }}

  verify-image: #image
    permissions:
      id-token: write
      attestations: read
      contents: read
      packages: read
      actions: read
    needs: [attest-image]
    runs-on: ubuntu-latest
    steps:
      - name: Run verify-image logic
        if: ${{ inputs.verify-image }}
        uses: ./.github/workflows/rw-hp-verify.yaml
        with:
          build-type: image
          registry: ${{ inputs.registry }}
          image-digest: ${{ needs.attest-image.outputs.image-digest }}
          cert-identity: ${{ inputs.cert-identity }}
          autogov-verify-version: ${{ inputs.autogov-verify-version }}
      - name: No-op if verify-image is false
        if: ${{ !inputs.verify-image }}
        run: echo "verify-image skipped"


  run-opa-image: #image
    permissions:
      id-token: write
      attestations: read
      packages: read
      actions: read
    needs: [verify-image, attest-image]
    runs-on: ubuntu-latest
    steps:
      - name: Run OPA logic
        if: ${{ inputs.run-opa-image }}
        uses: ./.github/workflows/rw-hp-run-opa.yaml
        with:
          build-type: image
          registry: ${{ inputs.registry }}
          image-digest: ${{ needs.attest-image.outputs.image-digest }}
          subject-name: ${{ github.repository }}
          ignore-dependency-vulnerabilities: ${{ inputs.ignore-dependency-vulnerabilities }}
      - name: No-op if run-opa-image is false
        if: ${{ !inputs.run-opa-image }}
        run: echo "run-opa-image skipped"

  test-dep: #image
    permissions:
      contents: write
      id-token: write
      actions: read
    needs: [verify-image, attest-image, run-opa-image]
    runs-on: ubuntu-latest
    steps:
      - name: Print results-artifact-id
        if: ${{ inputs.run-opa-image }}
        run: echo ${{ needs.run-opa-image.outputs.results-artifact-id }}
      - name: No-op if run-opa-image is false
        if: ${{ !inputs.run-opa-image }}
        run: echo "test-dep skipped because run-opa-image is false"


  test-opa-output:
    needs: [run-opa-image]
    runs-on: ubuntu-latest
    steps:
      - name: Echo OPA results artifact id
        if: ${{ inputs.run-opa-image }}
        run: |
          echo "OPA results artifact id: ${{ needs.run-opa-image.outputs.results-artifact-id }}"
      - name: No-op if run-opa-image is false
        if: ${{ !inputs.run-opa-image }}
        run: echo "test-opa-output skipped because run-opa-image is false"
  release-image: #image
    if: ${{ inputs.release-image }}
    permissions:
      contents: write
      id-token: write
      actions: read
    needs: [verify-image, attest-image, run-opa-image]
    uses: ./.github/workflows/rw-hp-release.yaml
    secrets: inherit
    with:
      build-type: image
      image-digest: ${{ needs.attest-image.outputs.image-digest }}
      attest-build-attestation-artifact-id: ${{ needs.attest-image.outputs.attest-build-attestation-artifact-id }}
      attest-metadata-attestation-artifact-id: ${{ needs.attest-image.outputs.attest-metadata-attestation-artifact-id }}
      attest-sbom-attestation-artifact-id: ${{ needs.attest-image.outputs.attest-sbom-attestation-artifact-id }}
      attest-dependency-scan-attestation-artifact-id: ${{ needs.attest-image.outputs.attest-dependency-scan-attestation-artifact-id }}
      results-artifact-id: ${{ needs.run-opa-image.outputs.results-artifact-id }}
      publish-attestations: ${{ inputs.publish-attestations }}
