name: Verify High Permissions Reuseable Workflow

on:
  workflow_call:
    inputs:
      build-type:
        description: 'Specify the type of build: "image" or "blob".'
        required: true
        type: string
      subject-name:
        description: >
          Subject name as it should appear in the attestation. Required unless
          "subject-path" is specified, in which case it will be inferred from the
          path.
        default: ${{ github.repository }}
        required: false
        type: string
      image-digest:
        description: The digest of the image that was built and pushed
        default: ${{ inputs.build-type == 'image' && github.event.needs.build.outputs.image-digest }}
        required: false
        type: string
      registry:
        description: >
          The container registry to use.
        default: ghcr.io
        required: false
        type: string
      blob-artifact-id:
        description: The artifact-id of the build artifacts.
        default: ${{ inputs.build-type == 'blob' && github.event.needs.build.outputs.blob-artifact-id }}
        type: string
      cert-identity:
        description: >
          The certificate identity of the signer workflow, or builder, used in the verify job to ensure artifacts and attestations can be verified against the source repository and correct workflow using the gh-cli (e.g. --cert-identity flag). If verifying an image, the workflow name should be rw-<permissions_path>-attest-image.yaml, if verifying blob(s), the workflow name should be rw-<permissions_path>-attest-blob.yaml.
        required: true
        type: string
      github-token:
        description: >
          The GitHub token set throughout the reuseable workflow including the composite (build) action.
        default: ''
        required: false
        type: string
      workflow-runner-label:
        description: The label of the workflow runner
        default: ubuntu-latest
        required: false
        type: string
      autogov-verify-version:
        description: The autogov-verify version to use.
        required: false
        type: string
        default: v0.4.3
      use-cert-identity-list:
        description: Whether to use cert-identity-list for validation
        required: false
        type: boolean
        default: ${{ github.repository != 'liatrio/liatrio-gh-autogov-workflows' }}

permissions: {}

env:
  GH_TOKEN: ${{ inputs.github-token || github.token }}
  ATTESTATIONS_FOLDER: ./attestations
  ARTIFACTS_FOLDER: ./artifacts

jobs:
  verify-high-perms:
    permissions:
      id-token: write
      attestations: read
      packages: read
      actions: read
    runs-on: ${{ inputs.workflow-runner-label }}
    steps:
      - name: Fail if Runner is self-hosted
        if: ${{ runner.environment != 'github-hosted' }}
        run: |
          echo "Job is running on a self-hosted runner. Terminating job..."
          exit 1
      - name: Validate Inputs
        if: ${{ runner.environment == 'github-hosted' }}
        run: |
          if [[ "${{ inputs.build-type }}" == "image" && -z "${{ inputs.image-digest }}" ]]; then
            echo "Error: image-digest is required for build-type 'image'."
            exit 1
          elif [[ "${{ inputs.build-type }}" == "blob" && -z "${{ inputs.blob-artifact-id}}" ]]; then
            echo "Error: blob-artifact-id is required for build-type 'blob'."
            exit 1
          fi
      - name: Login to GitHub Container Registry
        if: ${{ inputs.build-type == 'image' }}
        uses: docker/login-action@74a5d142397b4f367a81961eba4e8cd7edddf772 # v3.4.0
        with:
          registry: ${{ inputs.registry }}
          username: ${{ github.actor }}
          password: ${{ inputs.github-token || github.token }}
      - name: Create Attestations and Artifacts Folders
        run: mkdir ${{ env.ATTESTATIONS_FOLDER }} && mkdir ${{ env.ARTIFACTS_FOLDER }}
      - name: Download Blob Artifact(s)
        if: ${{ inputs.build-type == 'blob' }}
        uses: actions/download-artifact@d3f86a106a0bac45b974a628896c90dbdf5c8093 # v4.3.0
        with:
          github-token: ${{ inputs.github-token || github.token }}
          artifact-ids: ${{ inputs.blob-artifact-id }}
          path: ${{ env.ARTIFACTS_FOLDER }}
          merge-multiple: true
      - name: Download Blob Artifact Attestation(s)
        if: ${{ inputs.build-type == 'blob' }}
        run: |
          cd ${{ env.ATTESTATIONS_FOLDER }}
          find ../${{ env.ARTIFACTS_FOLDER }} -type f -exec gh attestation download {} --repo ${{ github.repository }} \;
      - uses: octo-sts/action@6177b4481c00308b3839969c3eca88c96a91775f # v1.0.0
        id: octo-sts
        with:
          scope: liatrio
          identity: autogov-infra
      - name: Install autogov-verify
        env:
          GH_TOKEN: ${{ steps.octo-sts.outputs.token }}
        run: |
          gh release download ${{ inputs.autogov-verify-version }} \
            --repo liatrio/autogov-verify \
            --pattern "autogov-verify"
          chmod +x autogov-verify
      - name: Verification of Image Attestation(s)
        if: ${{ inputs.build-type == 'image' }}
        run: |
          set +x
          ./autogov-verify \
            --artifact-digest ${{ format('{0}/{1}', inputs.registry, inputs.subject-name) }}@${{ inputs.image-digest }} \
            --cert-identity "${{ inputs.cert-identity }}" \
            ${{ inputs.use-cert-identity-list && '--cert-identity-list https://raw.githubusercontent.com/liatrio/liatrio-gh-autogov-workflows/main/cert-identities.json' || '' }} \
            --source-ref "${{ github.ref }}"
      - name: Online Verification of Blob Attestation(s)
        if: ${{ inputs.build-type == 'blob' }}
        run: |
          set +x
          find ${{ env.ARTIFACTS_FOLDER }} -type f | while read -r ARTIFACT; do
              ./autogov-verify \
                --blob-path ${ARTIFACT} \
                --cert-identity "${{ inputs.cert-identity }}" \
                ${{ inputs.use-cert-identity-list && '--cert-identity-list https://raw.githubusercontent.com/liatrio/liatrio-gh-autogov-workflows/main/cert-identities.json' || '' }} \
                --source-ref "${{ github.ref }}"
          done
