name: Verify High Permissions Reuseable Workflow

on:
  workflow_call:
    inputs:
      build-type:
        description: 'Specify the type of build: "image" or "blob".'
        required: true
        type: string
      subject-name:
        description: >
          Subject name as it should appear in the attestation. Required unless
          "subject-path" is specified, in which case it will be inferred from the
          path.
        default: ${{ github.repository }}
        required: false
        type: string
      image-digest:
        description: The digest of the image that was built and pushed
        default: ${{ inputs.build-type == 'image' && github.event.needs.build.outputs.image-digest }}
        required: false
        type: string
      registry:
        description: >
          The container registry to use.
        default: ghcr.io
        required: false
        type: string
      blob-artifact-id:
        description: The artifact-id of the build artifacts.
        default: ${{ inputs.build-type == 'blob' && github.event.needs.build.outputs.blob-artifact-id }}
        type: string
      cert-identity:
        description: >
          The certificate identity of the signer workflow, or builder, used in the verify job to ensure artifacts and attestations can be verified against the source repository and correct workflow using the gh-cli (e.g. --cert-identity flag). If verifying an image, the workflow name should be rw-<permissions_path>-attest-image.yaml, if verifying blob(s), the workflow name should be rw-<permissions_path>-attest-blob.yaml.
        required: true
        type: string
      github-token:
        description: >
          The GitHub token set throughout the reuseable workflow including the composite (build) action.
        default: ''
        required: false
        type: string
      workflow-runner-label:
        description: The label of the workflow runner
        default: ubuntu-latest
        required: false
        type: string

permissions: {}

env:
  GH_TOKEN: ${{ inputs.github-token || github.token }}
  ATTESTATIONS_FOLDER: ./attestations
  ARTIFACTS_FOLDER: ./artifacts

jobs:
  verify-high-perms:
    permissions:
      id-token: write
      attestations: read
      packages: read
    runs-on: ${{ inputs.workflow-runner-label }}
    steps:
      - name: Fail if Runner is self-hosted
        if: ${{ runner.environment != 'github-hosted' }}
        run: |
          echo "Job is running on a self-hosted runner. Terminating job..."
          exit 1
      - name: Validate Inputs
        if: ${{ runner.environment == 'github-hosted' }}
        run: |
          if [[ "${{ inputs.build-type }}" == "image" && -z "${{ inputs.image-digest }}" ]]; then
            echo "Error: image-digest is required for build-type 'image'."
            exit 1
          elif [[ "${{ inputs.build-type }}" == "blob" && -z "${{ inputs.blob-artifact-id}}" ]]; then
            echo "Error: blob-artifact-id is required for build-type 'blob'."
            exit 1
          fi
      - name: Login to GitHub Container Registry
        if: ${{ inputs.build-type == 'image' }}
        uses: docker/login-action@9780b0c442fbb1117ed29e0efdff1e18412f7567 # v3.3.0
        with:
          registry: ${{ inputs.registry }}
          username: ${{ github.actor }}
          password: ${{ inputs.github-token || github.token }}
      - name: Create Attestations and Artifacts Folders
        run: mkdir ${{ env.ATTESTATIONS_FOLDER }} && mkdir ${{ env.ARTIFACTS_FOLDER }}
      - name: Install actions/artifact Library
        if: ${{ inputs.build-type == 'blob' }}
        run: npm install @actions/artifact@2.2.1
      - name: Download Blob Artifact(s)
        if: ${{ inputs.build-type == 'blob' }}
        uses: actions/github-script@60a0d83039c74a4aee543508d2ffcb1c3799cdea # v7.0.1
        env:
          ARTIFACT_ID: ${{ inputs.blob-artifact-id }}
        with:
          script: |
            const { DefaultArtifactClient } = require('@actions/artifact');
            const artifactClient = new DefaultArtifactClient();
            const artifactId = process.env.ARTIFACT_ID;

            if (!artifactId) {
              throw new Error('Artifact ID is not defined');
            }

            await artifactClient.downloadArtifact(artifactId, { path: process.env.ARTIFACTS_FOLDER });
            console.log(`Downloaded artifact with ID: ${artifactId} to ${process.env.ARTIFACTS_FOLDER}`);
      - name: Download Blob Artifact Attestation(s)
        if: ${{ inputs.build-type == 'blob' }}
        run: |
          cd ${{ env.ATTESTATIONS_FOLDER }}
          for ARTIFACT in ../${{ env.ARTIFACTS_FOLDER }}/*; do
              gh attestation download "$ARTIFACT" --repo ${{ github.repository }}
          done
      - name: Process Sigstore Bundle(s)
        if: ${{ inputs.build-type == 'blob' }}
        run: cat ${{ env.ATTESTATIONS_FOLDER }}/*.jsonl > ${{ env.ATTESTATIONS_FOLDER }}/sigstore-bundle.jsonl
      - uses: octo-sts/action@6177b4481c00308b3839969c3eca88c96a91775f # v1.0.0
        id: octo-sts
        with:
          scope: liatrio
          identity: autogov-infra
      - name: Install autogov-verify
        env:
          GH_TOKEN: ${{ steps.octo-sts.outputs.token }}
        run: |
          gh release download \
            --repo liatrio/autogov-verify \
            --pattern "autogov-verify"
          chmod +x autogov-verify
      - name: Verify Attestation
        if: ${{ inputs.build-type == 'image' }}
        run: |
          set +x
          ./autogov-verify \
            --artifact-digest ${{ format('{0}/{1}', inputs.registry, inputs.subject-name) }}@${{ inputs.image-digest }} \
            --cert-identity "${{ inputs.cert-identity }}" \
            --expected-ref "${{ github.ref }}"
      - name: Online Verification of Blob Attestation(s)
        if: ${{ inputs.build-type == 'blob' }}
        run: |
          set +x
          for ARTIFACT in ${{ env.ARTIFACTS_FOLDER }}/*; do
              ./autogov-verify \
                --blob-path ${ARTIFACT} \
                --cert-identity "${{ inputs.cert-identity }}" \
                --expected-ref "${{ github.ref }}"
          done
