name: Attest Image High Permissions Reuseable Workflow

on:
  workflow_call:
    inputs:
      subject-name:
        description: >
          Subject name as it should appear in the attestation. Required unless
          "subject-path" is specified, in which case it will be inferred from the
          path.
        required: true
        type: string
      registry:
        description: Container registry to push image.
        required: false
        default: ghcr.io
        type: string
      use-low-perms:
        description: >
          Primarily for demo purposes and specific only to the build-image composite action so that it is unnecessary to manually change it when wanting to flip from high permissions to low permissions.
        default: false
        required: false
        type: boolean
      show-summary:
        description: >
          Whether to attach a list of generated attestations to the workflow run
          summary page. Defaults to true.
        default: true
        required: false
        type: boolean
      workflow-runner-label:
        description: >
          The label used for runner/OS selection, examples:
          https://docs.github.com/en/actions/writing-workflows/choosing-where-your-workflow-runs/choosing-the-runner-for-a-job#example-specifying-an-operating-system.
        required: false
        default: ubuntu-latest
        type: string
      github-token:
        description: >
          The GitHub token set throughout the reuseable workflow including the composite (build) action.
        required: false
        type: string
    outputs:
      image-digest:
        description: The image digest of the image that was built from the build-image job.
        value: ${{ jobs.build-high-perms.outputs.image-digest }}
      attest-build-attestation-artifact-id:
        description: The artifact-id of the build provenance attestation artifact.
        value: ${{ jobs.attest-build-high-perms.outputs.provenance-artifact-id }}
      attest-metadata-attestations-artifact-id:
        description: The artifact-id of the custom metadata attestation artifact.
        value: ${{ jobs.attest-metadata-high-perms.outputs.metadata-artifact-id }}
      attest-sbom-attestations-artifact-id:
        description: The artifact-id of the SBOM attestation artifact.
        value: ${{ jobs.attest-sbom-high-perms.outputs.sbom-artifact-id }}

permissions: {}

env:
  ARTIFACTS_FOLDER: ./artifacts
  ATTESTATIONS_FOLDER: ./attestations

jobs:
  build-high-perms:
    permissions:
      contents: read
      packages: write
    runs-on: ${{ inputs.workflow-runner-label }}
    outputs:
      image-digest: ${{ steps.build-image.outputs.image-digest }}
    steps:
      - name: Fail if Runner is self-hosted
        if: ${{ runner.environment != 'github-hosted' }}
        run: |
          echo "Job is running on a self-hosted runner. Terminating job..."
          exit 1
      - name: Checkout code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          ref: ${{ github.sha }}
          persist-credentials: false
      - name: Build Image
        if: ${{ runner.environment == 'github-hosted' }}
        id: build-image
        uses: ./.github/actions/build-image
        with:
          subject-name: ${{ inputs.subject-name }}
          use-low-perms: ${{ inputs.use-low-perms }}

  attest-build-high-perms:
    runs-on: ${{ inputs.workflow-runner-label }}
    needs: build-high-perms
    permissions:
      id-token: write
      attestations: write
      packages: write
    outputs:
      provenance-artifact-id: ${{ steps.upload-provenance.outputs.artifact-id }}
    steps:
      - name: Fail if Runner is self-hosted
        if: ${{ runner.environment != 'github-hosted' }}
        run: |
          echo "Job is running on a self-hosted runner. Terminating job..."
          exit 1
      - name: Login to GitHub Container Registry
        if: ${{ runner.environment == 'github-hosted' }}
        uses: docker/login-action@9780b0c442fbb1117ed29e0efdff1e18412f7567 # v3.3.0
        with:
          registry: ${{ inputs.registry }}
          username: ${{ github.actor }}
          password: ${{ github.token }}
      - name: Attest Provenance
        id: attest-build-provenance
        uses: actions/attest-build-provenance@ef244123eb79f2f7a7e75d99086184180e6d0018 # v1.4.4
        with:
          subject-name: ${{ inputs['subject-name'] }}
          subject-digest: ${{ needs.build-high-perms.outputs.image-digest }}
          github-token: ${{ inputs.github-token || github.token }}
          push-to-registry: true
      - name: Rename Provenance Bundle
        run: |
          mkdir ${{ env.ATTESTATIONS_FOLDER }}
          mv ${{ steps.attest-build-provenance.outputs.bundle-path }} ${{ env.ATTESTATIONS_FOLDER }}/attest-build-provenance-attestation.jsonl
      - name: Upload Provenance Sigstore Bundle
        id: upload-provenance
        uses: actions/upload-artifact@b4b15b8c7c6ac21ea08fcf65892d2ee8f75cf882 # v4.4.3
        with:
          name: image-build-provenance-attestation-high-perms
          path: ${{ env.ATTESTATIONS_FOLDER }}/attest-build-provenance-attestation.jsonl
          if-no-files-found: error

  attest-metadata-high-perms:
    runs-on: ${{ inputs.workflow-runner-label }}
    needs: build-high-perms
    permissions:
      id-token: write
      attestations: write
      packages: write
    outputs:
      metadata-artifact-id: ${{ steps.upload-metadata.outputs.artifact-id }}
    steps:
      - name: Fail if Runner is self-hosted
        if: ${{ runner.environment != 'github-hosted' }}
        run: |
          echo "Job is running on a self-hosted runner. Terminating job..."
          exit 1
      - name: Login to GitHub Container Registry
        if: ${{ runner.environment == 'github-hosted' }}
        uses: docker/login-action@9780b0c442fbb1117ed29e0efdff1e18412f7567 # v3.3.0
        with:
          registry: ${{ inputs.registry }}
          username: ${{ github.actor }}
          password: ${{ github.token }}
      - name: Generate Metadata Attestation
        run: |
          echo '{
            "_type": "https://in-toto.io/Statement/v0.1",
            "metadata": {
              "workflowData": {
                "workflowRefPath": "${{ github.workflow_ref }}",
                "branch": "${{ github.ref_name }}",
                "buildWorkflowRunId": "${{ github.run_id }}",
                "event": "${{ github.event_name }}",
                "inputs": ${{ toJson(inputs) }}
              },
              "commitData": {
                "commitSHA": "${{ github.sha }}",
                "commitTimestamp": "${{ github.event.head_commit.timestamp }}"
              },
              "repositoryData": {
                "repository": "${{ github.repository }}",
                "repositoryId": "${{ github.repository_id }}",
                "githubServerURL": "${{ github.server_url }}"
              },
              "ownerData": {
                "owner": "${{ github.repository_owner }}",
                "ownerId": "${{ github.repository_owner_id }}"
              },
              "jobData": {
                "jobId": "${{ github.job }}",
                "runNumber": "${{ github.run_number }}",
                "action": "${{ github.action }}",
                "actor": "${{ github.actor }}",
                "status": "${{ job.status }}"
              },
              "runnerData": {
                "os": "${{ runner.os }}",
                "name": "${{ runner.name }}",
                "arch": "${{ runner.arch }}",
                "environment": "${{ runner.environment }}"
              }
            }
          }' > metadata.json && cat metadata.json | jq -r
      - name: Attest Metadata
        uses: actions/attest@67422f5511b7ff725f4dbd6fb9bd2cd925c65a8d # v1.4.1
        id: attest-metadata
        with:
          subject-name: ${{ inputs['subject-name'] }}
          subject-digest: ${{ needs.build-high-perms.outputs.image-digest }}
          predicate-type: 'https://cosign.sigstore.dev/attestation/v1'
          predicate-path: metadata.json
          push-to-registry: true
      - name: Rename Metadata Bundle
        run: |
          mkdir ${{ env.ATTESTATIONS_FOLDER }}
          mv ${{ steps.attest-metadata.outputs.bundle-path }} ${{ env.ATTESTATIONS_FOLDER }}/attest-metadata-attestation.jsonl
      - name: Upload Metadata Sigstore Bundle
        uses: actions/upload-artifact@b4b15b8c7c6ac21ea08fcf65892d2ee8f75cf882 # v4.4.3
        id: upload-metadata
        with:
          name: image-metadata-attestation-high-perms
          path: ${{ env.ATTESTATIONS_FOLDER }}/attest-metadata-attestation.jsonl
          if-no-files-found: error

  attest-sbom-high-perms:
    runs-on: ${{ inputs.workflow-runner-label }}
    needs: build-high-perms
    permissions:
      id-token: write
      attestations: write
      contents: read
      packages: write
    outputs:
      sbom-artifact-id: ${{ steps.upload-sbom.outputs.artifact-id }}
    steps:
      - name: Fail if Runner is self-hosted
        if: ${{ runner.environment != 'github-hosted' }}
        run: |
          echo "Job is running on a self-hosted runner. Terminating job..."
          exit 1
      - name: Login to GitHub Container Registry
        if: ${{ runner.environment == 'github-hosted' }}
        uses: docker/login-action@9780b0c442fbb1117ed29e0efdff1e18412f7567 # v3.3.0
        with:
          registry: ${{ inputs.registry }}
          username: ${{ github.actor }}
          password: ${{ github.token }}
      - name: Generate SBOM
        uses: anchore/sbom-action@251a468eed47e5082b105c3ba6ee500c0e65a764 # v0.17.6
        with:
          image: ${{ format('{0}/{1}@{2}', inputs.registry, github.repository, needs.build-high-perms.outputs.image-digest) }}
          format: cyclonedx-json
          output-file: sbom.cyclonedx.json
          upload-release-assets: false
          upload-artifact: false
          github-token: ${{ inputs.github-token || github.token }}
      - name: Log SBOM File
        run: cat sbom.cyclonedx.json | jq -r
      - name: Generate SBOM attestation
        id: attest-sbom
        uses: actions/attest-sbom@5026d3663739160db546203eeaffa6aa1c51a4d6 # v1.4.1
        with:
          subject-name: ${{ inputs['subject-name'] }}
          subject-digest: ${{ needs.build-high-perms.outputs.image-digest }}
          sbom-path: sbom.cyclonedx.json
          github-token: ${{ inputs.github-token || github.token }}
          push-to-registry: true
      - name: Rename SBOM Bundle
        run: |
          mkdir ${{ env.ATTESTATIONS_FOLDER }}
          mv ${{ steps.attest-sbom.outputs.bundle-path }} ${{ env.ATTESTATIONS_FOLDER }}/attest-sbom-attestation.jsonl
      - name: Upload SBOM Attestation
        id: upload-sbom
        uses: actions/upload-artifact@b4b15b8c7c6ac21ea08fcf65892d2ee8f75cf882 # v4.4.3
        with:
          name: image-sbom-attestation-high-perms
          path: ${{ env.ATTESTATIONS_FOLDER }}/attest-sbom-attestation.jsonl
          if-no-files-found: error
