name: Release Low Permissions Reuseable Workflow

on:
  workflow_call:
    inputs:
      build-type:
        description: 'Specify the type of build: "image" or "blob".'
        required: true
        type: string
      image-artifact-id:
        type: string
        description: The artifact-id of the build artifacts.
        default: ${{ inputs.build-type == 'image' && github.event.needs.build-low-perms.outputs.image-artifact-id }}
      blob-artifact-id:
        type: string
        description: The artifact-id of the build artifacts.
        default: ${{ inputs.build-type == 'blob' && github.event.needs.build-low-perms.outputs.blob-artifact-id }}
      attest-build-attestation-artifact-id:
        description: The artifact-id of the build provenance attestation artifact.
        default: ${{ github.event.needs.attest-build-low-perms.outputs.attest-build-attestation-artifact-id }}
        type: string
      attest-metadata-attestations-artifact-id:
        description: The artifact-id of the custom metadata attestation artifact.
        default: ${{ github.event.needs.attest-metadata-low-perms.outputs.build-artifact-id }}
        type: string
      attest-sbom-attestations-artifact-id:
        description: The artifact-id of the SBOM attestation artifact.
        default: ${{ github.event.needs.attest-sbom-low-perms.outputs.build-artifact-id }}
        type: string
      results-artifact-id:
        type: string
        description: The artifact-id of the attestation artifacts.
        required: true
        default: ${{ github.event.needs.run-opa.outputs.results-artifact-id }}
      workflow-runner-label:
        type: string
        description: The label of the workflow runner
        default: ubuntu-latest
      github-token:
        description: >
          The GitHub token set throughout the reuseable workflow including the composite (build) action.
        required: false
        type: string
    outputs:
      semantic-release-version:
        description: The version of the semantic release generated by the semantic-release action.
        value: ${{ jobs.release-high-perms.outputs.semantic-release-version }}

env:
  ARTIFACT_IDS: |
    ${{ inputs.attest-build-attestation-artifact-id }}
    ${{ inputs.attest-metadata-attestations-artifact-id }}
    ${{ inputs.attest-sbom-attestations-artifact-id }}
  BLOB_ARTIFACT_ID: ${{ inputs.build-type == 'blob' && inputs.blob-artifact-id || '' }}
  IMAGE_ARTIFACT_ID: ${{ inputs.build-type == 'image' && inputs.image-artifact-id || '' }}
  RESULTS_ARTIFACT_ID: ${{ inputs.results-artifact-id }}
  ATTESTATIONS_FOLDER: ./attestations
  ARTIFACTS_FOLDER: ./artifacts
  RESULTS_FOLDER: ./${{ inputs.build-type }}-results

permissions: {}

jobs:
  release-low-perms:
    runs-on: ${{ inputs.workflow-runner-label }}
    if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
    permissions:
      contents: write
      id-token: write
    outputs:
      semantic-release-version: ${{ steps.semantic-release.outputs.new_release_version }}
    steps:
      - name: Fail if Runner is self-hosted
        if: ${{ runner.environment != 'github-hosted' }}
        run: |
          echo "Job is running on a self-hosted runner. Terminating job..."
          exit 1
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          ref: ${{ github.sha }}
          persist-credentials: false
      - name: Install actions/artifact Library
        run: npm install @actions/artifact@2.1.11
        if: ${{ runner.environment == 'github-hosted'}}
      - name: Create Attestations and Artifacts Folders
        run: mkdir ${{ env.ATTESTATIONS_FOLDER }} && mkdir ${{ env.ARTIFACTS_FOLDER }}
      - name: Download Sigstore Bundle(s)
        uses: actions/github-script@60a0d83039c74a4aee543508d2ffcb1c3799cdea # v7.0.1
        with:
          script: |
            const { DefaultArtifactClient } = require('@actions/artifact');
            const artifactClient = new DefaultArtifactClient();
            const artifactIds = process.env.ARTIFACT_IDS.split('\n').map(id => id.trim()).filter(id => id);

            for (const artifactId of artifactIds) {
              if (!artifactId) {
                console.log('Skipping undefined artifact ID');
                continue;
              }

              await artifactClient.downloadArtifact(artifactId, { path: process.env.ATTESTATIONS_FOLDER });
              console.log(`Downloaded artifact with ID: ${artifactId} to ${process.env.ATTESTATIONS_FOLDER}`);
            }
      - name: Download Artifact(s)
        uses: actions/github-script@60a0d83039c74a4aee543508d2ffcb1c3799cdea # v7.0.1
        with:
          script: |
            const { DefaultArtifactClient } = require('@actions/artifact');
            const artifactClient = new DefaultArtifactClient();
            // Determine the artifact ID based on the build type
            const artifactId = process.env.BLOB_ARTIFACT_ID || process.env.IMAGE_ARTIFACT_ID;

            if (!artifactId) {
              throw new Error('Artifact ID is not defined');
            }

            await artifactClient.downloadArtifact(artifactId, { path: process.env.ARTIFACTS_FOLDER });
            console.log(`Downloaded artifact with ID: ${artifactId} to ${process.env.ARTIFACTS_FOLDER}`);
      - name: Process Sigstore Bundle(s)
        run: cat ${{ env.ATTESTATIONS_FOLDER }}/*.jsonl > ${{ env.ATTESTATIONS_FOLDER }}/sigstore-bundle.jsonl
      - name: Download opa-run Results
        uses: actions/github-script@60a0d83039c74a4aee543508d2ffcb1c3799cdea # v7.0.1
        with:
          script: |
            const { DefaultArtifactClient } = require('@actions/artifact');
            const artifactClient = new DefaultArtifactClient();
            const artifactId = process.env.RESULTS_ARTIFACT_ID;

            if (!artifactId) {
              throw new Error('Artifact ID is not defined');
            }

            await artifactClient.downloadArtifact(artifactId, { path: process.env.RESULTS_FOLDER });
            console.log(`Downloaded artifact with ID: ${artifactId} to ${process.env.RESULTS_FOLDER}`);
      - uses: octo-sts/action@6177b4481c00308b3839969c3eca88c96a91775f # v1.0.0
        id: octo-sts
        with:
          scope: ${{ github.repository }}
          identity: main-semantic-release
      - name: Semantic Release
        uses: cycjimmy/semantic-release-action@b1b432f13acb7768e0c8efdec416d363a57546f2 # v4.1.1
        id: semantic-release
        with:
          extra_plugins: |
            @semantic-release/git
            @semantic-release/changelog
            @semantic-release/exec
          dry_run: false
        env:
          GITHUB_TOKEN: ${{ steps.octo-sts.outputs.token }}
          GIT_AUTHOR_NAME: github-actions[bot]
          GIT_AUTHOR_EMAIL: github-actions[bot]@users.noreply.github.com
          GIT_COMMITTER_NAME: github-actions[bot]
          GIT_COMMITTER_EMAIL: github-actions[bot]@users.noreply.github.com
      - name: Upload Results/Sigstore Bundle as Release Asset
        if: steps.semantic-release.outputs.new_release_version != ''
        uses: softprops/action-gh-release@c95fe1489396fe8a9eb87c0abf8aa5b2ef267fda # v2.2.1
        with:
          files: |
            ${{ env.RESULTS_FOLDER }}/*
            ${{ env.ATTESTATIONS_FOLDER }}/*.jsonl
            ${{ env.ARTIFACTS_FOLDER }}/*
          tag_name: v${{ steps.semantic-release.outputs.new_release_version }}
          token: ${{ inputs.github-token || github.token }}
