name: Verify Low Permissions Reuseable Workflow

on:
  workflow_call:
    inputs:
      blob-artifact-id:
        type: string
        description: The artifact-id of the build artifacts.
        required: true
        default: ${{ github.event.needs.build-low-perms.outputs.blob-artifact-id }}
      attest-build-attestation-artifact-id:
        description: The artifact-id of the build provenance attestation artifact.
        default: ${{ github.event.needs.attest-build-low-perms.outputs.attest-build-attestation-artifact-id }}
        type: string
      attest-metadata-attestation-artifact-id:
        description: The artifact-id of the custom metadata attestation artifact.
        default: ${{ github.event.needs.attest-metadata-low-perms.outputs.build-artifact-id }}
        type: string
      attest-sbom-attestation-artifact-id:
        description: The artifact-id of the SBOM attestation artifact.
        default: ${{ github.event.needs.attest-sbom-low-perms.outputs.build-artifact-id }}
        type: string
      attest-dependency-scan-attestation-artifact-id:
        description: The artifact-id of the dependency scan attestation artifact.
        default: ${{ github.event.needs.attest-dependency-scan-low-perms.outputs.build-artifact-id }}
        type: string
      cert-identity:
        type: string
        description: >
          The certificate identity of the signer workflow, or builder, used in the verify job to ensure artifacts and attestations can be verified against the source repository and correct workflow using the gh-cli (e.g. --cert-identity flag). Since blob is the only build type that uses this workflow, the workflow name should be rw-lp-attest-blob.yaml
        required: true
      github-token:
        description: >
          The GitHub token set throughout the reuseable workflow including the composite (build) action.
        default: ''
        required: false
        type: string
      workflow-runner-label:
        type: string
        description: The label of the workflow runner
        required: false
        default: ubuntu-latest

permissions: {}

env:
  GH_TOKEN: ${{ inputs.github-token || github.token }}
  ARTIFACT_IDS: "${{ inputs.attest-build-attestation-artifact-id }},${{ inputs.attest-metadata-attestation-artifact-id }},${{ inputs.attest-sbom-attestation-artifact-id }},${{ inputs.attest-dependency-scan-attestation-artifact-id }}"
  ATTESTATIONS_FOLDER: ./attestations
  ARTIFACTS_FOLDER: ./artifacts

jobs:
  verify-low-perms:
    permissions:
      contents: read
      actions: read
    runs-on: ${{ inputs.workflow-runner-label }}
    steps:
      - name: Fail if Runner is self-hosted
        if: ${{ runner.environment != 'github-hosted' }}
        run: |
          echo "Job is running on a self-hosted runner. Terminating job..."
          exit 1
      - name: Download Trusted Roots
        run: gh attestation trusted-root > trusted_root.json
      - name: Create Attestations Folder
        run: mkdir ${{ env.ATTESTATIONS_FOLDER }}
      - name: Download Sigstore Bundle(s)
        uses: actions/download-artifact@d3f86a106a0bac45b974a628896c90dbdf5c8093 # v4.3.0
        with:
          github-token: ${{ inputs.github-token || github.token }}
          artifact-ids: ${{ env.ARTIFACT_IDS }}
          path: ${{ env.ATTESTATIONS_FOLDER }}
          merge-multiple: true
      - name: Process Sigstore Bundle(s)
        run: find ${{ env.ATTESTATIONS_FOLDER }} -name "*.jsonl" -exec cat {} \; > ${{ env.ATTESTATIONS_FOLDER }}/sigstore-bundle.jsonl
      - name: Process Sigstore Bundle for Offline Blob Verification
        run: |
          cp ${{ env.ATTESTATIONS_FOLDER }}/sigstore-bundle.jsonl ${{ env.ATTESTATIONS_FOLDER }}/all_attestations.jsonl
          cd ${{ env.ATTESTATIONS_FOLDER }}
          find . -name "*.jsonl" ! -name "all_attestations.jsonl" -delete
      - name: Download Blob Artifact(s)
        uses: actions/download-artifact@d3f86a106a0bac45b974a628896c90dbdf5c8093 # v4.3.0
        with:
          github-token: ${{ inputs.github-token || github.token }}
          artifact-ids: ${{ inputs.blob-artifact-id }}
          path: ${{ env.ARTIFACTS_FOLDER }}
          merge-multiple: true
      - name: Offline Verification of Blob Attestation(s)
        run: |
          set +x
          find ${{ env.ARTIFACTS_FOLDER }} -type f | while read -r ARTIFACT; do
            gh attestation verify \
              $ARTIFACT \
              --deny-self-hosted-runners \
              --repo ${{ github.repository }} \
              --cert-identity "${{ inputs.cert-identity }}" \
              --bundle ${{ env.ATTESTATIONS_FOLDER }}/all_attestations.jsonl \
              --custom-trusted-root trusted_root.json \
              --format json \
              --jq '.[].verificationResult.signature.certificate.sourceRepositoryRef' \
            | grep "^${{ github.ref }}$"

            gh attestation verify \
              $ARTIFACT \
              --deny-self-hosted-runners \
              --repo ${{ github.repository }} \
              --cert-identity "${{ inputs.cert-identity }}" \
              --bundle ${{ env.ATTESTATIONS_FOLDER }}/all_attestations.jsonl \
              --custom-trusted-root trusted_root.json \
              --format json \
              --jq '.[].verificationResult | {keys: (.statement.predicate.metadata.workflowData.inputs // {}) | keys}' \
            | grep -E \
              'blob-artifact-name|subject-path|workflow-runner-label|show-summary' | \
            jq -r
          done
