name: Attest Image Low Permissions Reuseable Workflow

on:
  workflow_call:
    inputs:
      subject-name:
        description: >
          Subject name as it should appear in the attestation. Required unless
          "subject-path" is specified, in which case it will be inferred from the
          path.
        required: true
        type: string
      image-artifact-name:
        description: The name of artifact for the image built from the build-image action.
        default: image-build-artifact-low-perms
        required: false
        type: string
      show-summary:
        description: >
          Whether to attach a list of generated attestations to the workflow run
          summary page. Defaults to true.
        default: true
        required: false
        type: boolean
      workflow-runner-label:
        description: >
          The label used for runner/OS selection, examples:
          https://docs.github.com/en/actions/writing-workflows/choosing-where-your-workflow-runs/choosing-the-runner-for-a-job#example-specifying-an-operating-system.
        required: false
        default: ubuntu-latest
        type: string
      github-token:
        description: >
          The GitHub token set throughout the reuseable workflow including the composite (build) action.
        required: false
        type: string
    outputs:
      image-artifact-id:
        description: The artifact-id of the image artifact.
        value: ${{ jobs.build-image-low-perms.outputs.image-artifact-id }}
      attest-build-attestation-artifact-id:
        description: The artifact-id of the build provenance attestation artifact.
        value: ${{ jobs.attest-image-low-perms.outputs.build-artifact-id }}
      attest-metadata-attestations-artifact-id:
        description: The artifact-id of the custom metadata attestation artifact.
        value: ${{ jobs.image-attest-metadata-low-perms.outputs.build-artifact-id }}
      attest-sbom-attestations-artifact-id:
        description: The artifact-id of the SBOM attestation artifact.
        value: ${{ jobs.image-attest-sbom-low-perms.outputs.build-artifact-id }}
      attest-dependency-scan-attestations-artifact-id:
        description: The artifact-id of the dependency scan attestation artifact.
        value: ${{ jobs.image-attest-dependency-scan-low-perms.outputs.dependency-scan-artifact-id }}

permissions: {}

env:
  ARTIFACTS_FOLDER: ./artifacts
  ATTESTATIONS_FOLDER: ./attestations

jobs:
  build-image-low-perms:
    permissions:
      contents: read
      packages: read
    runs-on: ${{ inputs.workflow-runner-label }}
    outputs:
      image-digest: ${{ steps.build-image.outputs.image-digest }}
      image-artifact-id: ${{ steps.upload-image.outputs.artifact-id }}
    steps:
      - name: Fail if Runner is self-hosted
        if: ${{ runner.environment != 'github-hosted' }}
        run: |
          echo "Job is running on a self-hosted runner. Terminating job..."
          exit 1
      - name: Checkout code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          ref: ${{ github.sha }}
          persist-credentials: false
      - name: Build Image
        if: ${{ runner.environment == 'github-hosted' }}
        id: build-image
        uses: ./.github/actions/build-image
        with:
          subject-name: ${{ inputs.subject-name }}
      - name: Upload Image
        id: upload-image
        uses: actions/upload-artifact@65c4c4a1ddee5b72f698fdd19549f0f0fb45cf08 # v4.6.0
        with:
          name: ${{ inputs.image-artifact-name }}
          path: /tmp/image.tar
          if-no-files-found: error

  attest-image-low-perms:
    runs-on: ${{ inputs.workflow-runner-label }}
    needs: build-image-low-perms
    permissions:
      id-token: write
      attestations: write
      contents: read
    env:
      ARTIFACT_ID: ${{ needs.build-image-low-perms.outputs.image-artifact-id }}
    outputs:
      build-artifact-id: ${{ steps.upload-provenance.outputs.artifact-id }}
    steps:
      - name: Fail if Runner is self-hosted
        if: ${{ runner.environment != 'github-hosted' }}
        run: |
          echo "Job is running on a self-hosted runner. Terminating job..."
          exit 1
      - name: Install actions/artifact Library
        if: ${{ runner.environment == 'github-hosted' }}
        run: npm install @actions/artifact@2.1.11
      - name: Download Image Artifact
        uses: actions/github-script@60a0d83039c74a4aee543508d2ffcb1c3799cdea # v7.0.1
        env:
          ARTIFACT_ID: ${{ needs.build-image-low-perms.outputs.image-artifact-id }}
        with:
          script: |
            const { DefaultArtifactClient } = require('@actions/artifact');
            const artifactClient = new DefaultArtifactClient();
            const artifactId = process.env.ARTIFACT_ID;

            if (!artifactId) {
              throw new Error('Artifact ID is not defined');
            }

            await artifactClient.downloadArtifact(artifactId, { path: process.env.ARTIFACTS_FOLDER });
            console.log(`Downloaded artifact with ID: ${artifactId} to ${process.env.ARTIFACTS_FOLDER}`);
      - name: Attest Provenance
        id: attest-build-provenance
        uses: actions/attest-build-provenance@7668571508540a607bdfd90a87a560489fe372eb # v2.1.0
        with:
          subject-name: ${{ inputs.subject-name }}
          subject-path: ${{ format('{0}/{1}', env.ARTIFACTS_FOLDER , 'image.tar') }}
          github-token: ${{ inputs.github-token || github.token }}
          push-to-registry: false
      - name: Rename Provenance Bundle
        run: |
          mkdir ${{ env.ATTESTATIONS_FOLDER }}
          mv ${{ steps.attest-build-provenance.outputs.bundle-path }} ${{ env.ATTESTATIONS_FOLDER }}/attest-build-provenance-attestation.jsonl
      - name: Upload Provenance Sigstore Bundle
        id: upload-provenance
        uses: actions/upload-artifact@65c4c4a1ddee5b72f698fdd19549f0f0fb45cf08 # v4.6.0
        with:
          name: image-build-provenance-attestation-low-perms
          path: ${{ env.ATTESTATIONS_FOLDER }}/attest-build-provenance-attestation.jsonl
          if-no-files-found: error

  image-attest-metadata-low-perms:
    runs-on: ${{ inputs.workflow-runner-label }}
    needs: build-image-low-perms
    permissions:
      id-token: write
      attestations: write
      contents: read
    outputs:
      build-artifact-id: ${{ steps.upload-metadata.outputs.artifact-id }}
    steps:
      - name: Fail if Runner is self-hosted
        if: ${{ runner.environment != 'github-hosted' }}
        run: |
          echo "Job is running on a self-hosted runner. Terminating job..."
          exit 1
      - name: Install actions/artifact Library
        if: ${{ runner.environment == 'github-hosted' }}
        run: npm install @actions/artifact@2.1.11
      - name: Download Image Artifact
        uses: actions/github-script@60a0d83039c74a4aee543508d2ffcb1c3799cdea # v7.0.1
        env:
          ARTIFACT_ID: ${{ needs.build-image-low-perms.outputs.image-artifact-id }}
        with:
          script: |
            const { DefaultArtifactClient } = require('@actions/artifact');
            const artifactClient = new DefaultArtifactClient();
            const artifactId = process.env.ARTIFACT_ID;

            if (!artifactId) {
              throw new Error('Artifact ID is not defined');
            }

            await artifactClient.downloadArtifact(artifactId, { path: process.env.ARTIFACTS_FOLDER });
            console.log(`Downloaded artifact with ID: ${artifactId} to ${process.env.ARTIFACTS_FOLDER}`);
      - name: Generate Metadata Attestation
        shell: bash
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: |
          VERSION="${GITHUB_SHA:0:7}-${GITHUB_RUN_NUMBER}"

          cat << EOF > metadata.json
          {
            "artifact": {
              "version": "${VERSION}",
              "digest": "${{ needs.build-image-low-perms.outputs.image-digest }}",
              "created": "$(date -u +"%Y-%m-%dT%H:%M:%SZ")",
              "type": "container-image",
              "registry": "local",
              "fullName": "${{ inputs.subject-name }}"
            },
            "repositoryData": {
              "repository": "${{ github.repository }}",
              "repositoryId": "${{ github.repository_id }}",
              "githubServerURL": "${{ github.server_url }}"
            },
            "ownerData": {
              "owner": "${{ github.repository_owner }}",
              "ownerId": "${{ github.repository_owner_id }}"
            },
            "runnerData": {
              "os": "${{ runner.os }}",
              "arch": "${{ runner.arch }}",
              "environment": "${{ runner.environment }}"
            },
            "workflowData": {
              "workflowRefPath": "${{ github.workflow_ref }}",
              "inputs": ${{ toJson(inputs) }},
              "branch": "${{ github.ref_name }}",
              "event": "${{ github.event_name }}"
            },
            "jobData": {
              "runNumber": "${{ github.run_number }}",
              "runId": "${{ github.run_id }}",
              "status": "${{ job.status }}",
              "triggeredBy": "${{ github.actor }}",
              "startedAt": "${{ github.event.workflow_run.created_at }}",
              "completedAt": "$(date -u +"%Y-%m-%dT%H:%M:%SZ")"
            },
            "commitData": {
              "sha": "${{ github.sha }}",
              "timestamp": "${{ github.event.head_commit.timestamp }}"
            },
            "organization": {
              "name": "${{ github.repository_owner }}"
            },
            "compliance": {
              "policyRef": "https://github.com/liatrio/demo-gh-autogov-policy-library",
              "controlIds": [
                "${{ github.repository_owner }}-PROVENANCE-001",
                "${{ github.repository_owner }}-SBOM-002",
                "${{ github.repository_owner }}-METADATA-003"
              ]
            },
            "security": {
              "permissions": {
                "id-token": "write",
                "attestations": "write",
                "packages": "read",
                "contents": "read"
              }
            }
          }
          EOF

          echo "Generated metadata:"
          cat metadata.json | jq '.'
      - name: Attest Metadata
        uses: actions/attest@63d2e98e267398337e9a17ec68a5c8d936cb9247 # v2.1.0
        id: attest-metadata
        with:
          subject-name: ${{ inputs.subject-name }}
          subject-path: ${{ format('{0}/{1}', env.ARTIFACTS_FOLDER , 'image.tar') }}
          predicate-type: 'https://cosign.sigstore.dev/attestation/v1'
          predicate-path: metadata.json
          push-to-registry: false
      - name: Rename Metadata Bundle
        run: |
          mkdir ${{ env.ATTESTATIONS_FOLDER }}
          mv ${{ steps.attest-metadata.outputs.bundle-path }} ${{ env.ATTESTATIONS_FOLDER }}/attest-metadata-attestation.jsonl
      - name: Upload Metadata Sigstore Bundle
        uses: actions/upload-artifact@65c4c4a1ddee5b72f698fdd19549f0f0fb45cf08 # v4.6.0
        id: upload-metadata
        with:
          name: attest-metadata-image-low-perms
          path: ${{ env.ATTESTATIONS_FOLDER }}/attest-metadata-attestation.jsonl
          if-no-files-found: error

  image-attest-sbom-low-perms:
    runs-on: ${{ inputs.workflow-runner-label }}
    needs: build-image-low-perms
    permissions:
      id-token: write
      attestations: write
      contents: read
    outputs:
      build-artifact-id: ${{ steps.upload-sbom.outputs.artifact-id }}
    steps:
      - name: Fail if Runner is self-hosted
        if: ${{ runner.environment != 'github-hosted' }}
        run: |
          echo "Job is running on a self-hosted runner. Terminating job..."
          exit 1
      - name: Install actions/artifact Library
        run: npm install @actions/artifact@2.1.11
        if: ${{ runner.environment == 'github-hosted' }}
      - name: Download Image Artifact
        uses: actions/github-script@60a0d83039c74a4aee543508d2ffcb1c3799cdea # v7.0.1
        env:
          ARTIFACT_ID: ${{ needs.build-image-low-perms.outputs.image-artifact-id }}
        with:
          script: |
            const { DefaultArtifactClient } = require('@actions/artifact');
            const artifactClient = new DefaultArtifactClient();
            const artifactId = process.env.ARTIFACT_ID;

            if (!artifactId) {
              throw new Error('Artifact ID is not defined');
            }

            await artifactClient.downloadArtifact(artifactId, { path: process.env.ARTIFACTS_FOLDER });
            console.log(`Downloaded artifact with ID: ${artifactId} to ${process.env.ARTIFACTS_FOLDER}`);
      - name: Generate SBOM
        uses: anchore/sbom-action@df80a981bc6edbc4e220a492d3cbe9f5547a6e75 # v0.17.9
        with:
          path: ${{ env.ARTIFACTS_FOLDER }}
          format: cyclonedx-json
          output-file: sbom.cyclonedx.json
          upload-release-assets: false
          upload-artifact: false
          github-token: ${{ inputs.github-token || github.token }}
      - name: Log SBOM File
        run: cat sbom.cyclonedx.json | jq -r
      - name: Generate SBOM attestation
        id: attest-sbom
        uses: actions/attest-sbom@cbfd0027ae731a5892db25ecd226930d7ffd19eb # v2.1.0
        with:
          subject-name: ${{ inputs.subject-name }}
          subject-path: ${{ format('{0}/{1}', env.ARTIFACTS_FOLDER , 'image.tar') }}
          sbom-path: sbom.cyclonedx.json
          github-token: ${{ inputs.github-token || github.token }}
          push-to-registry: false
      - name: Rename SBOM Bundle
        run: |
          mkdir ${{ env.ATTESTATIONS_FOLDER }}
          mv ${{ steps.attest-sbom.outputs.bundle-path }} ${{ env.ATTESTATIONS_FOLDER }}/attest-sbom-attestation.jsonl
      - name: Upload SBOM Attestation
        id: upload-sbom
        uses: actions/upload-artifact@65c4c4a1ddee5b72f698fdd19549f0f0fb45cf08 # v4.6.0
        with:
          name: image-sbom-attestation-low-perms
          path: ${{ env.ATTESTATIONS_FOLDER }}/attest-sbom-attestation.jsonl
          if-no-files-found: error

  image-attest-dependency-scan-low-perms:
    runs-on: ${{ inputs.workflow-runner-label }}
    needs: build-image-low-perms
    permissions:
      id-token: write
      attestations: write
      contents: read
    outputs:
      dependency-scan-artifact-id: ${{ steps.upload-dependency-scan.outputs.artifact-id }}
    steps:
      - name: Fail if Runner is self-hosted
        if: ${{ runner.environment != 'github-hosted' }}
        run: |
          echo "Job is running on a self-hosted runner. Terminating job..."
          exit 1
      - name: Checkout code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        if: ${{ runner.environment == 'github-hosted' }}
      - name: Scan current project
        uses: anchore/scan-action@abae793926ec39a78ab18002bc7fc45bbbd94342 # v6.0.0
        id: anchore-scan
        with:
          path: "."
          output-format: "json"
          output-file: "results.json"
          fail-build: "false"
      - name: Generate Dependency Scan Attestation
        run: |
          # Load values from results.json
          SCANNER_VERSION=$(jq -r '.descriptor.version' results.json)
          SCANNER_URI="https://github.com/anchore/grype/releases/tag/v$SCANNER_VERSION"
          DB_URI=$(jq -r '.descriptor.configuration.db."update-url"' results.json)
          DB_VERSION=$(jq -r '.descriptor.db.schemaVersion' results.json)
          DB_LAST_UPDATE=$(jq -r '.descriptor.db.built' results.json)
          SCAN_STARTED_ON=$(jq -r '.descriptor.db.built' results.json)
          SCAN_FINISHED_ON=$(jq -r '.descriptor.timestamp' results.json)

          # Collect vulnerabilities with updated severity structure
          jq -n --arg scannerUri "$SCANNER_URI" \
                --arg scannerVersion "$SCANNER_VERSION" \
                --arg dbUri "$DB_URI" \
                --arg dbVersion "$DB_VERSION" \
                --arg dbLastUpdate "$DB_LAST_UPDATE" \
                --arg scanStartedOn "$SCAN_STARTED_ON" \
                --arg scanFinishedOn "$SCAN_FINISHED_ON" \
                --argjson results "$(jq '[.matches[] | {
                  id: .vulnerability.id,
                  severity: [
                    { "method": "nvd", "score": .vulnerability.severity },
                    { "method": "cvss_score", "score": (.vulnerability.cvss[0].metrics.baseScore | tostring) }
                  ]
                }]' results.json)" \
                '{
                  scanner: {
                    uri: $scannerUri,
                    version: $scannerVersion,
                    db: {
                      uri: $dbUri,
                      version: $dbVersion,
                      lastUpdate: $dbLastUpdate
                    },
                    result: $results
                  },
                  metadata: {
                    scanStartedOn: $scanStartedOn,
                    scanFinishedOn: $scanFinishedOn
                  }
                }' > dep-scan.json
          echo "Generated dependency scanning results:"
          cat dep-scan.json | jq '.'
      - name: Install actions/artifact Library
        if: ${{ runner.environment == 'github-hosted' }}
        run: npm install @actions/artifact@2.1.11
      - name: Download Image Artifact
        uses: actions/github-script@60a0d83039c74a4aee543508d2ffcb1c3799cdea # v7.0.1
        env:
          ARTIFACT_ID: ${{ needs.build-image-low-perms.outputs.image-artifact-id }}
        with:
          script: |
            const { DefaultArtifactClient } = require('@actions/artifact');
            const artifactClient = new DefaultArtifactClient();
            const artifactId = process.env.ARTIFACT_ID;

            if (!artifactId) {
              throw new Error('Artifact ID is not defined');
            }

            await artifactClient.downloadArtifact(artifactId, { path: process.env.ARTIFACTS_FOLDER });
            console.log(`Downloaded artifact with ID: ${artifactId} to ${process.env.ARTIFACTS_FOLDER}`);
      - name: Attest Dependency Scan
        uses: actions/attest@63d2e98e267398337e9a17ec68a5c8d936cb9247 # v2.1.0
        id: attest-dep-scan
        with:
          subject-name: ${{ inputs.subject-name }}
          subject-path: ${{ format('{0}/{1}', env.ARTIFACTS_FOLDER , 'image.tar') }}
          predicate-type: 'https://in-toto.io/attestation/vulns/v0.1'
          predicate-path: dep-scan.json
          push-to-registry: false
      - name: Rename Dependency Scan Bundle
        run: |
          mkdir ${{ env.ATTESTATIONS_FOLDER }}
          mv ${{ steps.attest-dep-scan.outputs.bundle-path }} ${{ env.ATTESTATIONS_FOLDER }}/attest-dep-scan-attestation.jsonl
      - name: Upload Dependency Scan Sigstore Bundle
        uses: actions/upload-artifact@6f51ac03b9356f520e9adb1b1b7802705f340c2b # v4.5.0
        id: upload-metadata
        with:
          name: image-dep-scan-attestation-low-perms
          path: ${{ env.ATTESTATIONS_FOLDER }}/attest-dep-scan-attestation.jsonl
          if-no-files-found: error
