name: OPA Evaluation Low Permissions Reuseable Workflow

on:
  workflow_call:
    inputs:
      build-type:
        description: 'Specify the type of build: "image" or "blob".'
        required: true
        type: string
      attest-build-attestation-artifact-id:
        description: The artifact-id of the build provenance attestation artifact.
        required: true
        default: ${{ github.event.needs.attest-build-low-perms.outputs.attest-build-attestation-artifact-id }}
        type: string
      attest-metadata-attestations-artifact-id:
        description: The artifact-id of the custom metadata attestation artifact.
        required: true
        default: ${{ github.event.needs.attest-metadata-low-perms.outputs.build-artifact-id }}
        type: string
      attest-sbom-attestations-artifact-id:
        description: The artifact-id of the SBOM attestation artifact.
        required: true
        default: ${{ github.event.needs.attest-sbom-low-perms.outputs.build-artifact-id }}
        type: string
      workflow-runner-label:
        type: string
        description: The label of the workflow runner
        default: ubuntu-latest
      opa-version:
        description: The OPA version to use.
        required: false
        type: string
        default: 0.67.1
    outputs:
      results-artifact-id:
        description: The image digest of the image that was built from the build-image job.
        value: ${{ jobs.run-opa-low-perms.outputs.results-artifact-id }}

permissions: {}

env:
  GH_TOKEN: ${{ github.token }}
  POLICY_REPO_ACCESS: ${{ secrets.POLICY_REPO_ACCESS }}
  ARTIFACTS_FOLDER: ./artifacts
  ATTESTATIONS_FOLDER: ./attestations

jobs:
  run-opa-low-perms:
    continue-on-error: true
    outputs:
      results-artifact-id: ${{ steps.upload-results.outputs.artifact-id }}
    permissions:
      contents: read
    runs-on: ${{ inputs.workflow-runner-label }}
    steps:
      - name: Fail if Runner is self-hosted
        if: ${{ runner.environment != 'github-hosted' }}
        run: |
          echo "Job is running on a self-hosted runner. Terminating job..."
          exit 1

      - name: Setup OPA
        if: ${{ runner.environment == 'github-hosted' }}
        uses: open-policy-agent/setup-opa@34a30e8a924d1b03ce2cf7abe97250bbb1f332b5 # v2.2.0
        with:
          version: ${{ inputs.opa-version }}
      - name: Install actions/artifact Library
        run: npm install @actions/artifact@2.1.11
      - name: Create Attestations and Artifacts Folders
        run: mkdir ${{ env.ATTESTATIONS_FOLDER }} && mkdir ${{ env.ARTIFACTS_FOLDER }}
      - name: Download Sigstore Bundle(s)
        uses: actions/github-script@60a0d83039c74a4aee543508d2ffcb1c3799cdea # v7.0.1
        env:
          ARTIFACT_IDS: |
            ${{ inputs.attest-build-attestation-artifact-id }}
            ${{ inputs.attest-metadata-attestations-artifact-id }}
            ${{ inputs.attest-sbom-attestations-artifact-id }}
        with:
          script: |
            const { DefaultArtifactClient } = require('@actions/artifact');
            const artifactClient = new DefaultArtifactClient();
            const artifactIds = process.env.ARTIFACT_IDS.split('\n').map(id => id.trim()).filter(id => id);

            for (const artifactId of artifactIds) {
              if (!artifactId) {
                console.log('Skipping undefined artifact ID');
                continue;
              }

              await artifactClient.downloadArtifact(artifactId, { path: process.env.ATTESTATIONS_FOLDER });
              console.log(`Downloaded artifact with ID: ${artifactId} to ${process.env.ATTESTATIONS_FOLDER}`);
            }
      - name: Process Sigstore Bundle(s) for OPA Eval
        run: |
          set +x
          jq -s . ${{ env.ATTESTATIONS_FOLDER }}/*.jsonl \
          > ${{ env.ATTESTATIONS_FOLDER }}/sigstore-bundle.json
          rm ${{ env.ATTESTATIONS_FOLDER }}/*.jsonl
          cat ${{ env.ATTESTATIONS_FOLDER }}/sigstore-bundle.json | jq -r
      - name: Download Policy Bundle
        run: |
          set +x
          export GH_TOKEN=${{ env.POLICY_REPO_ACCESS }}
          gh release download \
            --repo ${{ github.repository_owner }}/demo-gh-autogov-policy-library \
            --pattern "bundle.tar.gz"
      - name: Run OPA Evals
        id: run-opa
        run: |
          set -x
          opa eval \
            --fail \
            --input ${{ env.ATTESTATIONS_FOLDER }}/sigstore-bundle.json \
            --bundle "bundle.tar.gz" \
            "data.governance.allow" >\
          policy-evaluation.json
          cat policy-evaluation.json | jq -r
      - name: Output Violations if failed
        if: ${{ failure() && steps.run-opa.outcome == 'failure' }}
        run: |
          set -x
          opa eval \
            --fail \
            --input ${{ env.ATTESTATIONS_FOLDER }}/sigstore-bundle.json \
            --bundle "bundle.tar.gz" \
            "data.governance.violations" >\
          policy-evaluation.json
          cat policy-evaluation.json | jq -r
      - name: Format Results
        if: success() || failure()
        run: |
          RESULT_STATUS=$(jq -r 'if ([.result[].expressions[].value | recurse(.[]?) | arrays | length > 0] | any) then "FAILED" else "PASSED" end' policy-evaluation.json)
          echo "RESULT_STATUS=$RESULT_STATUS" >> $GITHUB_ENV
          jq --arg status "$RESULT_STATUS" '{
            result: $status,
            violations: (
              if ([.result[].expressions[].value | recurse(.[]?) | arrays | length > 0] | any) then
                [.result[].expressions[].value | recurse(.[]?) | objects | to_entries[] |
                  {policy: .key, message: .value | arrays | .[] | strings}]
              else
                []
              end
            )
          }' policy-evaluation.json > results-${RESULT_STATUS}
          cat results-${RESULT_STATUS} | jq -r
          echo "### Policy Evaluation Summary" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "#### Result: $(jq -r '.result' results-${RESULT_STATUS})" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          if [ $(jq '.violations | length' results-${RESULT_STATUS}) -gt 0 ]; then
              echo "#### Violations:" >> $GITHUB_STEP_SUMMARY
              jq -r '
              reduce .violations[] as $v ({}; .[$v.policy] += [$v.message])
              | to_entries[]
              | .key + ":\n" + (.value | map("- " + .) | join("\n")) + "\n"
              ' results-${RESULT_STATUS} >> $GITHUB_STEP_SUMMARY
          fi
      - name: Upload Results
        if: success() || failure()
        id: upload-results
        uses: actions/upload-artifact@6f51ac03b9356f520e9adb1b1b7802705f340c2b # v4.5.0
        with:
          name: ${{ inputs.build-type == 'image' && 'image-results-' || inputs.build-type == 'blob' && 'blob-results-' }}${{ env.RESULT_STATUS }}
          path: results-${{ env.RESULT_STATUS }}
          if-no-files-found: error
