name: Reusable OPA Evaluation Workflow

on:
  workflow_call:
    inputs:
      build-type:
        description: 'Specify the type of build: "image" or "blob".'
        required: true
        type: string
      subject-name:
        description: >
          Subject name as it should appear in the attestation. Required unless
          "subject-path" is specified, in which case it will be inferred from the
          path.
        default: ghcr.io/${{ github.repository }}
        required: false
        type: string
      image-digest:
        type: string
        description: The digest of the image that was built and pushed
        required: false
        default: ${{ inputs.build-type == 'image' && github.event.needs.build.outputs.image-digest }}
      build-artifact-id:
        type: string
        description: The artifact-id of the build artifacts.
        required: false
        default: ${{ inputs.build-type == 'blob' && github.event.needs.build.outputs.build-artifact-id }}
      workflow-runner-label:
        type: string
        description: The label of the workflow runner
        default: ubuntu-latest
      registry:
        description: >
          The container registry to use.
        required: false
        type: string
        default: ghcr.io

env:
  GH_TOKEN: ${{ github.token }}
  RW_CW_POLICY_REPO_ACCESS: ${{ secrets.RW_CW_POLICY_REPO_ACCESS }}

jobs:
  run-opa:
    runs-on: ${{ inputs.workflow-runner-label }}
    steps:
      - name: Log in to GitHub Container Registry
        if: ${{ inputs.build-type == 'image' }}
        uses: docker/login-action@9780b0c442fbb1117ed29e0efdff1e18412f7567 # v3.3.0
        with:
          registry: ${{ inputs.registry }}
          username: ${{ github.actor }}
          password: ${{ github.token }}
      - name: Setup OPA
        uses: open-policy-agent/setup-opa@34a30e8a924d1b03ce2cf7abe97250bbb1f332b5 # v2.2.0
        with:
          version: 0.67.1
      - run: npm install @actions/artifact@2.1.9
        if: ${{ runner.environment == 'github-hosted' && inputs.build-type == 'blob' }}
      - name: Download Blob Artifact
        if: ${{ inputs.build-type == 'blob' }}
        uses: actions/github-script@v7
        env:
          ARTIFACT_ID: ${{ inputs.build-artifact-id }}
          ARTIFACTS_FOLDER: ./artifacts
          ATTESTATIONS_FOLDER: ./attestations
        with:
          script: |
            const { DefaultArtifactClient } = require('@actions/artifact');
            const artifactClient = new DefaultArtifactClient();
            const artifactId = process.env.ARTIFACT_ID;

            if (!artifactId) {
              throw new Error('Artifact ID is not defined');
            }

            await artifactClient.downloadArtifact(artifactId, { path: process.env.ARTIFACTS_FOLDER });
            console.log(`Downloaded artifact with ID: ${artifactId} to ${process.env.ARTIFACTS_FOLDER}`);
      - name: List Downloaded Blob Artifacts
        if: ${{ inputs.build-type == 'blob' }}
        run: ls -althR ./artifacts
      - name: Download artifacts for blob
        if: ${{ inputs.build-type == 'blob' }}
        run: |
          if [ -d "./artifacts" ]; then
            for FILE in "./artifacts"/*; do
              gh attestation download "$FILE" -o liatrio
            done
          else
            echo "Directory ./artifacts does not exist"
            exit 1
          fi
      - name: list downloaded sigstore bundle(s)
        if: ${{ inputs.build-type == 'blob' }}
        run: |
          set -x
          ls -althR ./artifacts
          ls -althR *.jsonl
      - name: cat sigstore bundle
        if: ${{ inputs.build-type == 'blob' }}
        run: |
          set -x
          cat *.jsonl | jq -r '.dsseEnvelope.payload' | base64 -d | jq -r
      - name: Download artifact attestation for image
        if: ${{ inputs.build-type == 'image' }}
        run: |
          gh attestation download oci://${{ inputs.subject-name }}@${{ inputs.image-digest }} -o liatrio
      - name: Download Policy Bundle
        run: |
          set +x
          export GH_TOKEN=${{ env.RW_CW_POLICY_REPO_ACCESS }}
          gh release download \
            --repo liatrio/demo-gh-autogov-policy-library \
            --pattern "bundle.tar.gz"
      - name: Run OPA Evals
        id: run-opa
        run: |
          set -x
          opa eval \
            --fail \
            --input ${{ inputs.image-digest.jsonl || '*.jsonl' }} \
            --bundle "bundle.tar.gz" \
            "data.governance.allow" >\
          policy-evaluation.json
          cat policy-evaluation.json | jq -r
      - name: Output Violations if failed
        if: ${{ failure() && steps.run-opa.outcome == 'failure' }}
        run: |
          set -x
          opa eval \
            --fail \
            --input ${{ inputs.image-digest.jsonl || '*.jsonl' }} \
            --bundle "bundle.tar.gz" \
            "data.governance.violations" >\
          policy-evaluation.json
          cat policy-evaluation.json | jq -r
      - name: Format Results
        if: success() || failure()
        run: |
          jq '{
            result: (
              if ([.result[].expressions[].value | recurse(.[]?) | arrays | length > 0] | any) then "FAILED" else "PASSED" end
            ),
            violations: (
              if ([.result[].expressions[].value | recurse(.[]?) | arrays | length > 0] | any) then
                [.result[].expressions[].value | recurse(.[]?) | objects | to_entries[] |
                 {policy: .key, message: .value | arrays | .[] | strings}]
              else
                []
              end
            )
          }' policy-evaluation.json > results
          cat results | jq -r
          echo "### Policy Evaluation Summary" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "#### Result: $(jq -r '.result' results)" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          if [ $(jq '.violations | length' results) -gt 0 ]; then
              echo "#### Violations:" >> $GITHUB_STEP_SUMMARY
              jq -r '
              reduce .violations[] as $v ({}; .[$v.policy] += [$v.message])
              | to_entries[]
              | .key + ":\n" + (.value | map("- " + .) | join("\n")) + "\n"
              ' results >> $GITHUB_STEP_SUMMARY
          fi
      - name: Upload results
        uses: actions/upload-artifact@50769540e7f4bd5e21e526ee35c689e35e0d6874 # v4.4.0
        with:
          name: ${{ inputs.build-type == 'image' && 'image-results' || inputs.build-type == 'blob' && 'blob-results' }}
          path: results
          if-no-files-found: error
      # ______________#
      # image cleaner #
      # ______________#
      - uses: actions/delete-package-versions@abd519f0d4139a1c79766c4859d3a301fb3a8daa
        with:
          package-name: ${{ github.event.repository.name }}
          package-type: 'container'
          owner: ${{ github.repository_owner }}
          min-versions-to-keep: 0
          ignore-versions: '^v(0|[1-9]\d*)\.0\.0$' # currently does not work as per https://github.com/actions/delete-package-versions/issues/88
          delete-only-untagged-versions: 'true'
