name: Reusable Release Workflow

on:
  workflow_call:

jobs:
  release:
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
    permissions:
      contents: write
    steps:
      - name: Run go-semantic-release
        uses: go-semantic-release/action@48d83acd958dae62e73701aad20a5b5844a3bf45 # v1.23.0
        id: go-semantic-release
        with:
          github-token: ${{ github.token }}
          changelog-generator-opt: emojis=true
          allow-initial-development-versions: true
