name: Reusable OPA Evaluation Workflow

on:
  workflow_call:
    inputs:
      image_digest:
        type: string
        description: The digest of the image that was built and pushed
        required: true
      workflow-runner-label:
        type: string
        description: The label of the workflow runner
        default: ubuntu-latest
      registry:
        description: >
          The container registry to use.
        required: false
        type: string
        default: ghcr.io

env:
  GH_TOKEN: ${{ github.token }}
  READ_CONTENT_GITHUB_TOKEN: ${{ secrets.READ_CONTENT_GITHUB_TOKEN }}

jobs:
  run-opa:
    runs-on: ${{ inputs.workflow-runner-label }}
    steps:
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@9780b0c442fbb1117ed29e0efdff1e18412f7567 # v3.3.0
        with:
          registry: ${{ inputs.registry }}
          username: ${{ github.actor }}
          password: ${{ github.token }}
      - name: Setup OPA
        uses: open-policy-agent/setup-opa@34a30e8a924d1b03ce2cf7abe97250bbb1f332b5 # v2.2.0
        with:
          version: 0.67.1
      - name: Download artifact attestation
        run: |
          gh attestation download \
            oci://${{ inputs.registry }}/${{ github.repository }}@${{ inputs.image_digest }} \
            -o liatrio
      - name: Download Policy Bundle
        run: |
          set +x
          export GH_TOKEN=${{ env.READ_CONTENT_GITHUB_TOKEN }}
          gh release download \
            --repo liatrio/demo-gh-autogov-policy-library \
            --pattern "bundle.tar.gz"
      - name: Run OPA Evals
        id: run-opa
        run: |
          set -x
          opa eval \
            --fail \
            --input ${{ inputs.image_digest }}.jsonl \
            --bundle "bundle.tar.gz" \
            "data.governance.all_passed" >\
          policy-evaluation.json
          cat policy-evaluation.json | jq -r
      - name: Output Violations
        if: ${{ failure() && steps.run-opa.outcome == 'failure' }}
        run: |
          set -x
          opa eval \
            --fail \
            --input ${{ inputs.image_digest }}.jsonl \
            --bundle "bundle.tar.gz" \
            "data.security.provenance.violations" >\
          policy-evaluation.json
          cat policy-evaluation.json | jq -r
      - name: Format Results
        if: success() || failure()
        run: |
          jq '{
            result: (
              if ([.result[].expressions[].value | type == "array" and length > 0] | any) then "FAILED" else "PASSED" end
            ),
            violations: (
              if ([.result[].expressions[].value | type == "array" and length > 0] | any) then
                [.result[].expressions[].value[] | select(type == "string")]
              else
                []
              end
            )
          }' policy-evaluation.json > results
          cat results | jq -r
          echo "### Policy Evaluation Summary" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "#### Result: $(jq -r '.result' results)" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "#### Violations: $(jq -r '.violations' results)" >> $GITHUB_STEP_SUMMARY
      # ______________#
      # image cleaner #
      # ______________#
      - uses: actions/delete-package-versions@abd519f0d4139a1c79766c4859d3a301fb3a8daa
        with:
          package-name: ${{ github.event.repository.name }}
          package-type: 'container'
          owner: ${{ github.repository_owner }}
          min-versions-to-keep: 0
          ignore-versions: '^v(0|[1-9]\d*)\.0\.0$' # currently does not work as per https://github.com/actions/delete-package-versions/issues/88
          delete-only-untagged-versions: 'true'
