name: Reusable OPA Evaluation Workflow

on:
  workflow_call:
    inputs:
      image_digest:
        type: string
        description: The digest of the image that was built and pushed
        required: true

env:
  GH_TOKEN: ${{ github.token }}
  READ_CONTENT_GITHUB_TOKEN: ${{ secrets.READ_CONTENT_GITHUB_TOKEN }}

jobs:
  run-opa:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@9780b0c442fbb1117ed29e0efdff1e18412f7567 # v3.3.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}
      - name: Setup OPA
        uses: open-policy-agent/setup-opa@34a30e8a924d1b03ce2cf7abe97250bbb1f332b5 # v2.2.0
        with:
          version: 0.67.1
      - name: Download artifact attestation
        run: |
          gh attestation download \
            oci://ghcr.io/${{ github.repository }}@${{ inputs.image_digest }} \
            -o liatrio
      - name: Download Policy Bundle
        run: |
          set +x
          export GH_TOKEN=${{ env.READ_CONTENT_GITHUB_TOKEN }}
          gh release download \
            --repo liatrio/demo-gh-autogov-policy-library \
            --pattern "bundle.tar.gz"
      - name: Run OPA Evals
        if: success() || failure()
        run: |
          set -x
          opa eval \
            --fail \
            --input ${{ inputs.image_digest }}.jsonl \
            --bundle "bundle.tar.gz" \
            "data.governance.all_passed" > policy-evaluation.json
            cat policy-evaluation.json | jq -r
      - name: Format Results
        run: |
          jq '{
            result: (
              if ([.result[].expressions[].value] | any(. == false)) then "FAILED" else "PASSED" end
            ),
            violations: (
              [.result[].expressions[]
                | select(.value == false)
                | {
                    "Policy Set": (.text | split(".") | .[1] + "." + .[2]),
                    "Results": .value
                  }
              ]
            )
          }' policy-evaluation.json > results
          jq -s 'reduce .[] as $item ({}; . * $item)' results > final_result
          cat final_result | jq -r

          echo "### Policy Evaluation Summary" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "#### Result: $(jq -r '.result' final_result)" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
