name: Reusable Verify Workflow

on:
  workflow_call:
    inputs:
      build-type:
        description: 'Specify the type of build: "image" or "blob".'
        required: true
        type: string
      subject-name:
        description: >
          Subject name as it should appear in the attestation. Required unless
          "subject-path" is specified, in which case it will be inferred from the
          path.
        default: ghcr.io/${{ github.repository }}
        required: false
        type: string
      image-digest:
        type: string
        description: The digest of the image that was built and pushed
        required: false
        default: ${{ inputs.build-type == 'image' && github.event.needs.build.outputs.image-digest }}
      build-artifact-id:
        type: string
        description: The artifact-id of the build artifacts.
        default: ${{ inputs.build-type == 'blob' && github.event.needs.build.outputs.build-artifact-id }}
      all-attestations-artifact-id:
        type: string
        description: The artifact-id of the attestation artifacts.
        required: false
        default: ${{ github.event.needs.build.outputs.all-attestations-artifact-id }}
      cert-identity:
        type: string
        description: >
          The --cert-identity of the signer workflow, or builder, used in the verify job ensuring artifacts and attestations can be verified with the gh-cli.
        default: https://github.com/liatrio/demo-gh-autogov-workflows/.github/workflows/rw-attest.yaml@refs/heads/main
        required: false
      workflow-runner-label:
        type: string
        description: The label of the workflow runner
        required: false
        default: ubuntu-latest
      registry:
        description: >
          The container registry to use.
        required: false
        type: string
        default: 'ghcr.io'

permissions: {}

env:
  GH_TOKEN: ${{ github.token }}

jobs:
  verify:
    permissions:
      id-token: write
      attestations: read
      packages: read
    runs-on: ${{ inputs.workflow-runner-label }}
    steps:
      - name: Check Runner Type
        if: ${{ runner.environment != 'github-hosted' }}
        run: |
          echo "Job is running on a self-hosted runner. Terminating job..."
          exit 1
      - name: Validate Inputs
        run: |
          if [[ "${{ inputs.build-type }}" == "image" && -z "${{ inputs.image-digest }}" ]]; then
            echo "Error: subject-digest is required for build-type 'image'."
            exit 1
          elif [[ "${{ inputs.build-type }}" == "blob" && -z "${{ inputs.build-artifact-id}}" ]]; then
            echo "Error: build-artifact-id is required for build-type 'blob'."
            exit 1
          fi
      - name: Login to GitHub Container Registry
        if: ${{ runner.environment == 'github-hosted' && inputs.build-type == 'image' }}
        uses: docker/login-action@9780b0c442fbb1117ed29e0efdff1e18412f7567 # v3.3.0
        with:
          registry: ${{ inputs.registry }}
          username: ${{ github.actor }}
          password: ${{ github.token }}
      - run: npm install @actions/artifact@2.1.11
        if: ${{ runner.environment == 'github-hosted' && inputs.build-type == 'blob' }}
      - name: Download Blob Artifact(s)
        if: ${{ inputs.build-type == 'blob' }}
        uses: actions/github-script@60a0d83039c74a4aee543508d2ffcb1c3799cdea # v7.0.1
        env:
          ARTIFACT_ID: ${{ inputs.build-artifact-id }}
          ARTIFACTS_FOLDER: ./artifacts
        with:
          script: |
            const { DefaultArtifactClient } = require('@actions/artifact');
            const artifactClient = new DefaultArtifactClient();
            const artifactId = process.env.ARTIFACT_ID;

            if (!artifactId) {
              throw new Error('Artifact ID is not defined');
            }

            await artifactClient.downloadArtifact(artifactId, { path: process.env.ARTIFACTS_FOLDER });
            console.log(`Downloaded artifact with ID: ${artifactId} to ${process.env.ARTIFACTS_FOLDER}`);
      - name: List Downloaded Blob Artifact(s)
        if: ${{ inputs.build-type == 'blob' }}
        run: ls -althR ./artifacts
      - name: Verify Image Attestation(s)
        if: ${{ inputs.build-type == 'image' }}
        run: |
          set +x
          gh attestation verify \
            oci://${{ inputs.subject-name }}@${{ inputs.image-digest }} \
            --repo ${{ github.repository }} \
            --deny-self-hosted-runners \
            --cert-identity \
            "${{ inputs.cert-identity }}" \
            --format json \
            --jq '.[].verificationResult.signature.certificate.sourceRepositoryRef' \
          | grep "^${{ github.ref }}$"

          gh attestation verify \
            oci://${{ inputs.subject-name }}@${{ inputs.image-digest }} \
            --repo ${{ github.repository }} \
            --deny-self-hosted-runners \
            --cert-identity \
            "${{ inputs.cert-identity }}" \
            --format json \
            --jq '.[].verificationResult | {keys: (.statement.predicate.metadata.workflowData.inputs // {}) | keys}' \
          | grep -E \
              'build-type|predicate-type|registry|sbom-format|sbom-output-file|sbom-path|show-summary|signer-workflow-cert-identity|subject-name|workflow-runner-label' | \
            jq -r
      - name: Verify Blob Attestation(s)
        if: ${{ inputs.build-type == 'blob' }}
        env:
          ARTIFACTS_FOLDER: ./artifacts
        run: |
          set +x
          for FILE in "$ARTIFACTS_FOLDER"/*; do
            gh attestation verify \
              $FILE \
              --deny-self-hosted-runners \
              --repo ${{ github.repository }} \
              --cert-identity "${{ inputs.cert-identity }}" \
              --format json \
              --jq '.[].verificationResult.signature.certificate.sourceRepositoryRef' \
            | grep \
                "^${{ github.ref }}$"

            gh attestation verify \
              $FILE \
              --deny-self-hosted-runners \
              --repo ${{ github.repository }} \
              --cert-identity "${{ inputs.cert-identity }}" \
              --format json \
              --jq '.[].verificationResult | {keys: (.statement.predicate.metadata.workflowData.inputs // {}) | keys}' \
            | grep -E \
                'build-type|predicate-type|blob-artifact-name|sbom-format|sbom-output-file|sbom-path|show-summary|signer-workflow-cert-identity|subject-path|workflow-runner-label' | \
              jq -r
          done
