name: Reusable Verify Workflow

on:
  workflow_call:
    inputs:
      build-type:
        description: 'Specify the type of build: "image" or "blob".'
        required: true
        type: string
      subject-name:
        description: >
          Subject name as it should appear in the attestation. Required unless
          "subject-path" is specified, in which case it will be inferred from the
          path.
        default: ghcr.io/${{ github.repository }}
        required: false
        type: string
      image-digest:
        type: string
        description: The digest of the image that was built and pushed
        required: false
        default: ${{ inputs.build-type == 'image' && github.event.needs.build.outputs.image-digest }}
      build-artifact-id:
        type: string
        description: The artifact-id of the build artifacts.
        default: ${{ inputs.build-type == 'blob' && github.event.needs.build.outputs.build-artifact-id }}
      verify_tag:
        type: string
        description: Optional tag for verification
        required: false
      workflow-runner-label:
        type: string
        description: The label of the workflow runner
        required: false
        default: ubuntu-latest
      registry:
        description: >
          The container registry to use.
        required: false
        type: string
        default: 'ghcr.io'

env:
  GH_TOKEN: ${{ github.token }}

jobs:
  verify:
    runs-on: ${{ inputs.workflow-runner-label }}
    steps:
      - name: Check runner type
        if: ${{ runner.environment != 'github-hosted' }}
        run: |
          echo "Job is running on a self-hosted runner. Terminating job..."
          exit 1
      - name: Checkout code
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
      - name: Log in to GitHub Container Registry
        if: ${{ runner.environment == 'github-hosted' && inputs.build-type == 'image' }}
        uses: docker/login-action@9780b0c442fbb1117ed29e0efdff1e18412f7567 # v3.3.0
        with:
          registry: ${{ inputs.registry }}
          username: ${{ github.actor }}
          password: ${{ github.token }}
      - run: npm install @actions/artifact@2.1.9
        if: ${{ runner.environment == 'github-hosted' && inputs.build-type == 'blob' }}
      - name: download-artifact
        if: ${{ inputs.build-type == 'blob' }}
        uses: actions/github-script@v7
        env:
          ARTIFACT_ID: ${{ inputs.build-artifact-id }}
          ARTIFACTS_FOLDER: ./artifacts
        with:
          script: |
            const { DefaultArtifactClient } = require('@actions/artifact');
            const artifactClient = new DefaultArtifactClient();
            const artifactId = process.env.ARTIFACT_ID;

            if (!artifactId) {
              throw new Error('Artifact ID is not defined');
            }

            await artifactClient.downloadArtifact(artifactId, { path: process.env.ARTIFACTS_FOLDER });
            console.log(`Downloaded artifact with ID: ${artifactId} to ${process.env.ARTIFACTS_FOLDER}`);
      - name: List downloaded artifacts
        if: ${{ inputs.build-type == 'blob' }}
        run: ls -althR ./artifacts
      - name: Check if in workflow repo
        if: ${{ github.repository == 'liatrio/demo-gh-autogov-workflows' }}
        run: echo "verify_tag=${{ github.ref }}" >> "$GITHUB_ENV"
      - name: Get latest commit SHA from main
        if: ${{ github.repository != 'liatrio/demo-gh-autogov-workflows' && !inputs.verify_tag }}
        env:
          GH_TOKEN: ${{ secrets.RW_CW_POLICY_REPO_ACCESS }}
        run: |
          latest_sha=$(gh api /repos/liatrio/demo-gh-autogov-workflows/commits/main | jq -r '.sha')
          echo "verify_tag=$latest_sha" >> $GITHUB_ENV
      - name: Set verify_tag from input
        if: ${{ inputs.verify_tag }}
        run: echo "verify_tag=${{ inputs.verify_tag }}" >> $GITHUB_ENV
      - name: Verify attestation
        if: ${{ inputs.build-type == 'image' }}
        run: |
          gh attestation verify \
            oci://${{ inputs.subject-name }}@${{ inputs.image-digest }} \
            --repo ${{ github.repository }} \
            --deny-self-hosted-runners \
            --cert-identity \
            "https://github.com/${{ github.repository }}/.github/workflows/rw-attest.yaml@${{ env.verify_tag }}" \
            --format json \
            --jq '.[].verificationResult.signature.certificate.sourceRepositoryRef' \
            | grep "^${{ env.verify_tag }}$"
      - name: Verify blob attestation
        if: ${{ inputs.build-type == 'blob' }}
        env:
          ARTIFACTS_FOLDER: ./artifacts
        run: |
          for FILE in "$ARTIFACTS_FOLDER"/*; do
            gh attestation verify \
              $FILE \
              --deny-self-hosted-runners \
              --repo ${{ github.repository }} \
              --cert-identity "https://github.com/${{ github.repository }}/.github/workflows/rw-attest.yaml@${{ env.verify_tag }}" \
              --format json --jq '.[].verificationResult.signature.certificate.sourceRepositoryRef' \
            | grep "^${{ env.verify_tag }}$"
          done
