name: Verify Image Attestations

on:
  workflow_call:
    inputs:
      image_digest:
        type: string
        description: The digest of the image that was built and pushed
        required: true

jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
      - name: Log in to GitHub Container Registry
        uses: ./.github/actions/login-ghcr
        with:
          gh_token: ${{ secrets.GITHUB_TOKEN }}
      - name: check workflow repo
        id: check-workflow-repo
        if: ${{ github.repository == 'liatrio/demo-gh-autogov-workflows' }}
        run: |
          echo "verify_tag=.*" >> "$GITHUB_ENV"
      - name: Get latest commit SHA from main
        id: get-sha
        if: ${{ github.repository != 'liatrio/demo-gh-autogov-workflows' }}
        run: |
          echo "verify_tag=$(gh api /repos/liatrio/demo-gh-autogov-workflows/commits/main | jq -r '.sha')" >> $GITHUB_ENV
      - name: Verify attestation
        id: verify
        run: |
          gh attestation \
          verify \
          oci://ghcr.io/${{ github.repository }}@${{ inputs.image_digest }} \
          -o liatrio \
          --cert-identity-regex \
          "^https:\/\/github\.com\/liatrio\/demo-gh-autogov-workflows\/\.github\/workflows\/[^\/]+\.yaml@${{ env.verify_tag }}$" \
          --format json
        # haven't decided on what direction to go in regards to what to validate against / saving this as an alternative:
        # "^https:\/\/github\.com\/liatrio\/demo-gh-autogov-workflows\/\.github\/workflows\/[^\/]+\.yaml@[a-f0-9]{40}$" \
