name: Pull Request Check and Release Caller Workflow

on:
  workflow_dispatch:
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - main
  push:
    branches:
      - main
    paths-ignore:
      - 'README.md'
      - 'catalog-info.yaml'
      - 'renovate.json'

permissions:
  id-token: write
  attestations: write
  packages: write
  contents: write

jobs:
  build-image:
    uses: ./.github/workflows/rw-build-image.yaml
  attest-image:
    needs: build-image
    uses: ./.github/workflows/rw-attest-image.yaml
    secrets: inherit
    with:
      image_digest: ${{ needs.build-image.outputs.image_digest }}
  attest-sbom:
    needs: build-image
    uses: ./.github/workflows/rw-attest-sbom.yaml
    secrets: inherit
    with:
      image_digest: ${{ needs.build-image.outputs.image_digest }}
  attest-blob:
    needs: build-image
    uses: ./.github/workflows/rw-attest-blob.yaml
    secrets: inherit
    with:
      image_digest: ${{ needs.build-image.outputs.image_digest }}
  verify:
    needs: [build-image, attest-image, attest-sbom, attest-blob]
    uses: ./.github/workflows/rw-verify.yaml
    secrets: inherit
    with:
      image_digest: ${{ needs.build-image.outputs.image_digest }}
  run-opa:
    needs: [build-image, verify]
    uses: ./.github/workflows/rw-run-opa.yaml
    secrets: inherit
    with:
      image_digest: ${{ needs.build-image.outputs.image_digest }}
  release:
    needs: [build-image, run-opa]
    uses: ./.github/workflows/rw-release.yaml
    secrets: inherit
